Feature/installation guides run wsl
ThundeRatz/ROSGazeboGuide pull request #10
Opened 2021-03-29 14:30 UTC by Drebt

Olá. Venho aqui com a PR do tutorial de como rodar o projeto pelo WSL.

2021-03-30 15:27 UTC, VanderSant commented on HowToRun/RunOnWSL.md
> +O que acabou de acontecer? Bom, você acabou de usar o **git** para copiar um repositório que se encontra no **GitHub**, igual ao lugar onde você está lendo esse tutorial. Basicamente, é um site que a
```suggestion
O que acabou de acontecer? Bom, você acabou de usar o **git** para copiar um repositório que se encontra no **GitHub**, igual ao lugar onde você está lendo esse tutorial. Basicamente, é um site que armazena códigos para ficar fácil de grupos grandes ou pequenos de pessoas trabalharem no mesmo programa. Se você tem interesse em saber mais, converse com um dos professores ou monitores da disciplina! O que você copiou foi o modelo do carrinho, que se encontra [nesse link aqui](https://github.com/ThundeRatz/gazebo_modelo_carrinho.git).
```

2021-03-30 15:32 UTC, VanderSant commented on HowToRun/RunOnWSL.md
> +O que isso vai fazer é contruir o ambiente do projeto, usando como base aquilo que você baxiou do **GitHub**. Deve demorar um pouquinho mas não se assuste. Apenas fique na paz e no agurado. Assim que
```suggestion
O que isso vai fazer é construir o ambiente do projeto, usando como base aquilo que você baixou do **GitHub**. Deve demorar um pouquinho mas não se assuste. Apenas fique na paz e no aguardo. Assim que terminar rode o comando a seguir:
```

2021-03-30 15:33 UTC, VanderSant commented on HowToRun/RunOnWSL.md
> +E pronto, você só precisa agora usar o comando
```suggestion
E pronto, agora você só precisa usar o comando
```

2021-03-30 15:34 UTC, VanderSant commented on HowToRun/RunOnWSL.md
> +Agora que vocês tem WSL, ROS, Gazebo e XServer devidamente instalado nos seus computadores chegamos a parte mais legal de todas, rodar o projeto! Para isso precisamos fazer uma pasta para conter os d
```suggestion
Agora que vocês tem WSL, ROS, Gazebo e XServer devidamente instalado nos seus computadores chegamos a parte mais legal de todas, rodar o projeto! Para isso precisamos fazer uma pasta para conter os devidos arquivos. Primeiramente, certifique-se que seu servidor de XServer está rodando. Caso contrário, não teremos a janela do Gazebo aparecendo na nossa tela. Tudo certo? Então abra seu WSL e rode os seguintes comandos para criar o diretório do projeto e entrar nele.
```

2021-03-30 15:35 UTC, VanderSant commented on HowToRun/RunOnWSL.md
> +Caso você tenha percebido, temos uma pasta com um nome mais genérico dentro de uma com o código da disciplina. É nessa pasta genérica onde os arquivos do projeto ficarão, enquando que vamos usar o di
```suggestion
Caso você tenha percebido, temos uma pasta com um nome mais genérico dentro de uma com o código da disciplina. É nessa pasta genérica onde os arquivos do projeto ficarão, enquanto que vamos usar o diretório da disciplina para conter os arquivos de construção. Pode soar meio confuso mas eventualmente, durante o restante do tutorial, tudo vai ficar mais simples. 
```

2021-03-30 15:36 UTC, VanderSant commented on HowToRun/RunOnWSL.md
> +Agora que você tem os arquivos chegamos em uma parte que pode dar problema, instalar ainda mais coisas. O projeto em si tem algumas dependencias especificas que ainda não se econtram no seu computado
```suggestion
Agora que você tem os arquivos chegamos em uma parte que pode dar problema, instalar ainda mais coisas. O projeto em si tem algumas dependências especificas que ainda não se encontram no seu computador. Para baixar elas, rode o comando a seguir:
```

2021-03-30 15:37 UTC, VanderSant commented on HowToRun/RunOnWSL.md
> +Daqui pra frente é programar o carrinho ele, se divirta e que a diciplina seja um sucesso!
```suggestion
Sempre que você fechar o terminal do WSL e voltar você terá que executar o ```source ~/devel/setup.bash``` dentro da pasta ```/PMR3100/```. Caso contrário, você encontrará um erro ao tentar rodar o projeto.

E é isso. Agora você já sabe rodar o projeto direto do WSL. Se tiver acontecido algum problema durante o tutorial entre em contato com algum dos monitores que eles estão mais do que felizes em ajudar.

Daqui pra frente é programar o carrinho ele, se divirta e que a disciplina seja um sucesso!
```

2021-03-30 15:40 UTC, VanderSant commented
Ficou muito bom (extremamente bonito, diga-se de passagem), Luna!
Só sugeri algumas correçõezinhas.

2021-03-30 16:27 UTC, VanderSant commented on HowToRun/RunOnWSL.md
> +
```suggestion
Sempre que você fechar o terminal do WSL e voltar você terá que executar o ```source devel/setup.bash``` dentro da pasta ```/PMR3100/```. Caso contrário, você encontrará um erro ao tentar rodar o projeto.

```

2021-03-30 16:35 UTC, VanderSant commented on HowToRun/RunOnWSL.md
> +Daqui pra frente é programar o carrinho ele, se divirta e que a diciplina seja um sucesso!
```suggestion
Sempre que você fechar o terminal do WSL e voltar você terá que executar o ```source devel/setup.bash``` dentro da pasta ```/PMR3100/```. Caso contrário, você encontrará um erro ao tentar rodar o projeto.

E é isso. Agora você já sabe rodar o projeto direto do WSL. Se tiver acontecido algum problema durante o tutorial entre em contato com algum dos monitores que eles estão mais do que felizes em ajudar.

Daqui pra frente é programar o carrinho ele, se divirta e que a disciplina seja um sucesso!
```

2021-03-30 16:46 UTC, VanderSant commented on HowToRun/RunOnWSL.md
> +Daqui pra frente é programar o carrinho ele, se divirta e que a diciplina seja um sucesso!
```suggestion
Sempre que você fechar o terminal do WSL e voltar você terá que executar o ```source devel/setup.bash``` dentro da pasta ```/PMR3100/```. Caso contrário, você encontrará um erro ao tentar rodar o projeto.

E é isso. Agora você já sabe rodar o projeto direto do WSL. Se tiver acontecido algum problema durante o tutorial entre em contato com algum dos monitores que eles estão mais do que felizes em ajudar.

Daqui pra frente é programar o carrinho ele, se divirta e que a disciplina seja um sucesso!
```

2021-03-30 17:42 UTC, lucastrschneider reviewed
Tirando esse detalhezinho ali no final do texto, achei tudo bem explicadinho e didático, muito bom.

Um comentário mais geral que eu tinha pra fazer é sobre a nomenclatura das pastas. Quando no meio do texto vc usa ```/PMR3100/``` ou ```/src/``` da pra entender que você ta falando em relação a pasta atual, mas essa é a nomenclatura para caminho absoluto não é?
Vocês acham que faz sentido tirar a barra do começo pra deixar claro que é um caminho relativo ou será que pode ficar confuso? Ou então tirar as duas barras, já que é só o nome da pasta, não um caminho de fato? Não sei, o que vocês acham?

2021-03-30 17:42 UTC, lucastrschneider commented on HowToRun/RunOnWSL.md
> +Daqui pra frente é programar o carrinho ele, se divirta e que a disciplina seja um sucesso!
Acho que aqui sobrou esse "ele" no final da primeira frase

2021-03-30 17:42 UTC, lucastrschneider commented on HowToRun/RunOnWSL.md
> +Para rodar o comando você vai ter que fornecer a seu senha já que fazem uso do ```sudo```.
Acho que aqui seria "faz uso"

2021-03-30 21:31 UTC, Drebt commented on HowToRun/RunOnWSL.md
> +Daqui pra frente é programar o carrinho ele, se divirta e que a disciplina seja um sucesso!
Sobrou mesmo. Isso era por que antes tinha só o "ele". Ajeitarei

2021-03-30 21:39 UTC, Drebt commented
> Tirando esse detalhezinho ali no final do texto, achei tudo bem explicadinho e didático, muito bom.
> 
> Um comentário mais geral que eu tinha pra fazer é sobre a nomenclatura das pastas. Quando no meio do texto vc usa `/PMR3100/` ou `/src/` da pra entender que você ta falando em relação a pasta atual, mas essa é a nomenclatura para caminho absoluto não é?
> Vocês acham que faz sentido tirar a barra do começo pra deixar claro que é um caminho relativo ou será que pode ficar confuso? Ou então tirar as duas barras, já que é só o nome da pasta, não um caminho de fato? Não sei, o que vocês acham?

Sobre isso, acho que seria uma boa só tirar as barras mesmo já que estou falando de estar dentro da pasta. Nem me passou pela cabeça essa confusão de diretório vs caminho. Acham que eu só tiro as barras mesmo?

2021-04-04 15:26 UTC, LucasHaug requested changes
> > Tirando esse detalhezinho ali no final do texto, achei tudo bem explicadinho e didático, muito bom.
> > Um comentário mais geral que eu tinha pra fazer é sobre a nomenclatura das pastas. Quando no meio do texto vc usa `/PMR3100/` ou `/src/` da pra entender que você ta falando em relação a pasta atual, mas essa é a nomenclatura para caminho absoluto não é?
> > Vocês acham que faz sentido tirar a barra do começo pra deixar claro que é um caminho relativo ou será que pode ficar confuso? Ou então tirar as duas barras, já que é só o nome da pasta, não um caminho de fato? Não sei, o que vocês acham?
> 
> Sobre isso, acho que seria uma boa só tirar as barras mesmo já que estou falando de estar dentro da pasta. Nem me passou pela cabeça essa confusão de diretório vs caminho. Acham que eu só tiro as barras mesmo?

Acho que é bom tirar as narras mesmo.

2021-04-04 15:26 UTC, LucasHaug commented on HowToRun/RunOnWSL.md
> +
```suggestion
```

2021-04-04 15:26 UTC, LucasHaug commented on HowToRun/RunOnWSL.md
> +Esse primeiro comando cria a pasta ```/PMR3100/``` e dentro dela cria também a pasta ```/src/```. Já o segundo, te leva para a pasta recém criada. Se acostume a ver esse ```cd``` já que ele será freq
```suggestion
Esse primeiro comando cria a pasta ```/PMR3100/``` e dentro dela cria também a pasta ```/src/```. Já o segundo, te leva para a pasta recém criada. Se acostume a ver esse ```cd``` já que ele será frequentemente usado nesse guia para navegar entre os diretórios usando a linha de comando. Como pode ver pelo ```~/PMR3100/src$``` em azul, estamos na pasta ```/src/```.
```

2021-04-04 15:26 UTC, LucasHaug commented on HowToRun/RunOnWSL.md
> +
```suggestion
```

2021-04-04 15:26 UTC, LucasHaug commented on HowToRun/RunOnWSL.md
> +O que acabou de acontecer? Bom, você acabou de usar o **git** para copiar um repositório que se encontra no **GitHub**, parecido com o lugar onde você está lendo esse tutorial. Basicamente, é um site
Sobre aqui, tem aquilo que a gente comentou lá na reunião sobre git e tals, sobre mandar baixarem o zip.

2021-04-04 15:26 UTC, LucasHaug commented on HowToRun/RunOnWSL.md
> +
```suggestion
```

2021-04-04 15:26 UTC, LucasHaug commented on HowToRun/RunOnWSL.md
> +Agora, volte para a pasta ```/PMR3100/``` usando o comando
```suggestion
Agora, volte para a pasta ```/PMR3100/``` usando o comando:

```

2021-04-04 15:26 UTC, LucasHaug commented on HowToRun/RunOnWSL.md
> +e finalmente execute o
```suggestion

E finalmente execute o:

```

2021-04-04 15:26 UTC, LucasHaug commented on HowToRun/RunOnWSL.md
> +
```suggestion
![Running catkin_make](../assets/gif/Run_WSL/Running_catkin_make.gif)
```

2021-04-04 15:26 UTC, LucasHaug commented on HowToRun/RunOnWSL.md
> +
```suggestion
```

2021-04-04 15:26 UTC, LucasHaug commented on HowToRun/RunOnWSL.md
> +E pronto, agora você só precisa usar o comando
Acho que daria pra juntar as frase pro comando não ficar no meio e falar que é o carrinho base, porque eles vão ter que fazer o deles né.

```suggestion
E pronto, agora você só precisa usar o comando abaixo para abrir o Gazebo na sua tela juntamente com o lindo carrinho base da disciplina.
```

2021-04-04 15:26 UTC, LucasHaug commented on HowToRun/RunOnWSL.md
> +que o Gazebo deve abrir na sua tela juntamente com o lindo carrinho da disciplina.
```suggestion
```

2021-04-04 15:26 UTC, LucasHaug commented on HowToRun/RunOnWSL.md
> +
```suggestion
```

2021-04-04 15:50 UTC, LucasHaug commented on HowToRun/RunOnWSL.md
> +O que acabou de acontecer? Bom, você acabou de usar o **git** para copiar um repositório que se encontra no **GitHub**, parecido com o lugar onde você está lendo esse tutorial. Basicamente, é um site
E disso também, acho que eles vão acabar vendo mais no GitHub Pages, do que no Github em si

2021-04-04 16:01 UTC, LucasHaug commented on HowToRun/RunOnWSL.md
> +![WSL + ROS Diagram](../assets/img/Run_WSL/Cover.jpg)
```suggestion

![WSL + ROS Diagram](../assets/img/Run_WSL/Cover.jpg)
```

2021-04-05 12:13 UTC, Drebt commented on HowToRun/RunOnWSL.md
> +O que acabou de acontecer? Bom, você acabou de usar o **git** para copiar um repositório que se encontra no **GitHub**, parecido com o lugar onde você está lendo esse tutorial. Basicamente, é um site
Beleza, já vou ajeitar isso

2021-04-16 14:25 UTC, FelipeGdM submitted a review, later dismissed
Show de bola!

O Rafael já até testou e aprovou, então tamo em casa

2021-04-17 19:17 UTC, mariarezende07 approved these changes
Eu achei o texto muito bem escrito e bem direto. Fez o que prometeu.
Curti mtt

2021-04-18 14:38 UTC, LucasHaug requested changes

2021-04-18 19:48 UTC, FelipeGdM approved these changes

2021-04-18 19:54 UTC, LucasHaug approved these changes
Bom acho que é bom ter a parte de rodar o script do pygame, mas não precisa ser aqui, vou deixar aprovado já então

2021-04-18 20:19 UTC, merged