Hotfix/rafael suggestions
ThundeRatz/ROSGazeboGuide pull request #13
Opened 2021-04-02 22:18 UTC by GabrielKishida

Fazendo o PR dessa branch de Hotfixes, em que corrigimos os o que o Rafael pediu quanto aos textos.

2021-04-04 15:31 UTC, LucasHaug requested changes
Show ~~, só dei request de TOC~~.

2021-04-04 15:31 UTC, LucasHaug commented on InstalationGuides/ROSGazeboWSL.md
> +Para resolver esse problema, use o seguinte comando:
```suggestion
Para resolver esse problema, use o seguinte comando:

```

2021-04-04 15:31 UTC, LucasHaug commented on InstalationGuides/ROSGazeboWSL.md
> +Depois de corrigir esse problema, pode-se seguir normalmente o tutorial.
```suggestion

Depois de corrigir esse problema, pode-se seguir normalmente o tutorial. 
```

2021-04-05 02:56 UTC, LucasHaug approved these changes

2021-04-05 12:22 UTC, Drebt approved these changes

2021-04-05 16:42 UTC, merged