Tutorial de como utilizar o GitHub Desktop
ThundeRatz/ROSGazeboGuide pull request #15
Opened 2021-04-07 20:45 UTC by mariarezende07

Eu tinha comentado sobre, daí já peguei pra fazer. Eu dei uma introduçãozinha e coloquei os links dos vídeos utilizados no PS. Não sei se ficou muito claro mas acho que pode pelo menos dar uma ajuda caso a gente precise. E mesmo que não precisarmos, vai pelo menos resolver um pouco toda a questão de falta de comunicação que eu reclamei sobre a matéria.

<s>Sim eu fiz esse antes do sobre o Gazebo pq tô travada no texto</s>

2021-04-09 12:55 UTC, FelipeGdM submitted a review, later dismissed
Sucesso total! Achei bem top a explicação

Eu sugeriria fazer aquele macetinho pra centralizar as imagens, mas é detalhe de rodapé

2021-04-09 17:17 UTC, GabrielKishida submitted a review, later dismissed
Achei que ficou tudo muito top!
Você usou muito bem os gifs, e deixou tudo de uma forma bem clara e metódica.

Acho que ficou um pouco vago a correlação entre o projeto de carrinhos e o uso de Git e GitHub, mas imagino que isso fique um pouco fora de contexto para se colocar neste tutorial.
Dito isso, acho que está muito bom do jeito que tá! Boa, Mafê!

2021-04-10 04:24 UTC, febagni requested changes
Muito boa as explicações! Os gifs ficaram bem top msm! Mais uma "detalhe de rodapé" seria você fazer um índice pra facilitar  a navegação. E uma outra coisa, você acha que é bom explicar/mencionar as diferenças entre Git e GitHub?
Mas de resto, excelente trabalho!  
PS; vou deixar o request changes, só por conta do nome do R maíusculo no nome da equipe dashduashduahsd

2021-04-10 04:24 UTC, febagni commented on InstalationGuides/UsingGithubDesktop.md
> +Para uma abordagem mais detalhada, é altamente recomendável assistir as aulas de Git disponibilizadas pela equipe Thunderatz no Youtube. As duas aulinhas são curtas e tem cerca de 13 minutos cada, e
```suggestion
Para uma abordagem mais detalhada, é altamente recomendável assistir as aulas de Git disponibilizadas pela equipe ThundeRatz no YouTube. As duas aulinhas são curtas e tem cerca de 13 minutos cada, e estão disponíveis nos seguintes links:
```

2021-04-16 05:53 UTC, VanderSant reviewed
Muito boa toda a explicação mafê! 
Assim como o @febagni , acho que seria interessante mencionar a diferença entre o Git e GitHub também. De resto, não tenho nada a acrescentar.

2021-04-16 13:40 UTC, FelipeGdM approved these changes
Acredito que a explicação da diferença entre git e github foge um pouco do escopo desse guia, por mim já tá show de bola

2021-04-18 17:24 UTC, LucasHaug requested changes
Comentei só umas coisinhas simplesinhas, de resto show.

Acho que a gente não tem que mexer nesse tutorial aqui, só uma coisinhas que eu tava pensando enquanto tava vendo que acho que a gente tem que se preocupar mais talvez na documentação do template em python é como juntar as duas coisas, porque tipo aqui a gente manda eles criarem um repositório vazio e lá a gente só manda eles baixarem o zip, aí acho que talvez ou mandar eles fazerem um fork ou só copiar as coisas do zip mesmo e commitar ahsuhasuhsuahsuhsu, não sei o que acham??

2021-04-18 17:24 UTC, LucasHaug commented on InstalationGuides/UsingGithubDesktop.md
> +![Join in GitHub](../assets/gif/GitHub/join.gif){: .d-block .mx-auto}
```suggestion

![Join in GitHub](../assets/gif/GitHub/join.gif){: .d-block .mx-auto}
```

2021-04-18 17:24 UTC, LucasHaug commented on InstalationGuides/UsingGithubDesktop.md
> +e, caso você vá para a página inicial, seu repositório estará disponível na barra ao lado:
```suggestion
E, caso você vá para a página inicial, seu repositório estará disponível na barra ao lado:
```

2021-04-18 17:24 UTC, LucasHaug commented on InstalationGuides/UsingGithubDesktop.md
> +Daí, é só digitar os emails/nomes de usuário dos seus colegas de grupo.
```suggestion

Daí, é só digitar os emails/nomes de usuário dos seus colegas de grupo.
```

2021-04-18 17:24 UTC, LucasHaug commented on InstalationGuides/UsingGithubDesktop.md
> +Agora, vamos deixar isso um pouco de lado e entender como iremos mexer nos nossos projetos por meio dessa plataforma. Para isso, vamos instalar a ferramenta **GitHub Desktop**, que permite que você u
```suggestion

Agora, vamos deixar isso um pouco de lado e entender como iremos mexer nos nossos projetos por meio dessa plataforma. Para isso, vamos instalar a ferramenta **GitHub Desktop**, que permite que você use o Git sem a necessidade de saber utilizar a linha de comando.
```

2021-04-18 17:24 UTC, LucasHaug commented on InstalationGuides/UsingGithubDesktop.md
> +Caso houverem mudanças, clique em **Pull from origin**.
```suggestion
Caso hajam mudanças, clique em **Pull from origin**.
```

2021-04-18 17:24 UTC, LucasHaug commented on InstalationGuides/UsingGithubDesktop.md
> +Após isso, uma tela de costumização irá aparecer. Preencha de acordo com os seus interesses.
```suggestion
Após isso, uma tela de customização irá aparecer. Preencha de acordo com os seus interesses.
```

2021-04-19 21:06 UTC, mariarezende07 commented
> Comentei só umas coisinhas simplesinhas, de resto show.
> 
> Acho que a gente não tem que mexer nesse tutorial aqui, só uma coisinhas que eu tava pensando enquanto tava vendo que acho que a gente tem que se preocupar mais talvez na documentação do template em python é como juntar as duas coisas, porque tipo aqui a gente manda eles criarem um repositório vazio e lá a gente só manda eles baixarem o zip, aí acho que talvez ou mandar eles fazerem um fork ou só copiar as coisas do zip mesmo e commitar ahsuhasuhsuahsuhsu, não sei o que acham??

acho que mandar copiar > commitar é mais simples, mas daí tmb n sei

2021-04-20 00:15 UTC, febagni approved these changes
Ótimo trabalho! Tá check!

2021-04-20 00:33 UTC, guedeslucas1 reviewed
Muito top mesmo a explicação, achei bem didático e dinâmico. Só fiquei com uma pequena dúvida que eu deixei comentado aqui em baixo

2021-04-20 00:33 UTC, guedeslucas1 commented on InstalationGuides/UsingGithubDesktop.md
> +![Join in GitHub](../assets/gif/GitHub/join.gif){: .d-block .mx-auto}
Esse {: .d-block .mx-auto} deveria estar aparecendo em baixo das imagens no arquivo final mesmo?

2021-04-20 00:39 UTC, GabrielKishida reviewed
Essa é a segunda vez que eu passo aqui e vim para dizer que tá muito top de novo kkkkkk

Acho que a única coisa que falta pra ficar trincando é ver a questao do "{: .d-block .mx-auto}" que o @guedeslucas1 levantou.

2021-04-20 00:39 UTC, mariarezende07 commented on InstalationGuides/UsingGithubDesktop.md
> +![Join in GitHub](../assets/gif/GitHub/join.gif){: .d-block .mx-auto}
Então, ele serve pra centralizar as imagens. Pelo que eu entendi, ele aparece aqui mas some quando colocado no site, similar a [essa outra documentação](https://github.com/ThundeRatz/ROSGazeboGuide/blob/main/ROS/WhyToUse.md).

2021-04-20 00:45 UTC, guedeslucas1 commented on InstalationGuides/UsingGithubDesktop.md
> +![Join in GitHub](../assets/gif/GitHub/join.gif){: .d-block .mx-auto}
Check então!

2021-04-20 00:46 UTC, guedeslucas1 approved these changes
Muito top

2021-04-20 01:19 UTC, LucasHaug approved these changes

2021-04-20 01:19 UTC, merged