Documentação sobre o que é o gazebo
ThundeRatz/ROSGazeboGuide pull request #16
Opened 2021-04-09 06:17 UTC by mariarezende07

Nesta parte eu tentei falar um pouco sobre o que é um ambiente de simulação, o que são os arquivos que geram as simulações no Gazebo e explicar um pouquinho dos comandos que os alunos utilizarão para executar a simulação. Não sei se está 100% correto tudo, mas espero que esteja explicativo.

2021-04-09 13:21 UTC, FelipeGdM requested changes
Show de bola!

Uma coisa que eu não entendi no texto é a diferença entre "ferramentas de simulação" e "simulador". As duas expressões foram usadas de forma meio intercambiável no texto, mas acredito que isso pode causar alguma confusão entre os alunos

Achei bem daora a forma como vc esmiuça as partes de um projeto de simulação, porém eu senti falta de referências pra cada um dos tópicos, não precisa ser nada elaborado, pode ser a página correspondente na ROS wiki msm. No caso específico do URDF, é importante dizer que a sigla significa _Universal Robot Description Format_

Arquivos de mundo e de modelos por sua vez seguem o padrão SDFormat - _Simulation Description Format_

URDF - http://wiki.ros.org/urdf
SDFormat - http://sdformat.org/

Achei bem bacana a forma como vc quebrou o comando em partes pra explicar cada pedaço, uma sugestão que eu faria é acionar o link da nossa página sobre ROS como referência hehehe

No mais, era isso que eu tinha pra dizer. Fiquem bem e mantenham-se hidratados

2021-04-10 04:10 UTC, febagni requested changes
Excelente documentação! Deixei uns comentários mais pontuais e sugestões de alterações! :smile:

2021-04-10 04:10 UTC, febagni commented on Gazebo/WhatIs.md
> +Durante o desenvolvimento de projetos, é importante saber como ele irá se comportar em determinados ambientes. Neste contexto, as ferramentas de simulação tornam essa tarefa possível: elas permitem q
Será que vale a pena falar um pouco mais sobre a importância das simulações?  Que além de saber como o projeto vai se comportar sem precisar construí-lo de fato (manufaturar a parada toda), os resultados são geralmente tem uma acurácia boa em comparação a modelos analíticos, ajudam a encontrar "fenômenos/comportamentos inesperados" do sistema e facilitam análise e diversos tipos de testes (principalmente do tipo "e se..."), exatamente por estar no ambiente simulado. E tudo isso, representa redução de custos também, o que é muito importante em qualquer projeto.  E vale pensar também em sistemas críticos e como simulações são essenciais.

2021-04-16 16:19 UTC, FelipeGdM requested changes
Salve salve garotada

O texto tá show do bola, tem alguma coisinha ou outra de revisão de texto pra arrumar e uma questão de picuinha entre URDF/SDF. Resolvido isso pode dar merge

2021-04-16 16:19 UTC, FelipeGdM commented on Gazebo/WhatIs.md
> +Os arquivos de *launch* vão juntar tudo acima em apenas um arquivo para que sejamos capazes de abrir a simulação. Dentro do arquivo de *launch*, implementamos os *nodes*, o modelo do carrinho e da pi
```suggestion
Os arquivos de *launch* vão juntar tudo acima em apenas um arquivo para que sejamos capazes de abrir a simulação. Dentro do arquivo de *launch*, implementamos os *nodes*, o modelo do carrinho, da pista e os controles necessários para mover o carrinho. Para saber mais sobre arquivos de *launch*, sugiro dar uma olhada [**nesse link**](http://wiki.ros.org/roslaunch/XML).
```

2021-04-16 16:19 UTC, FelipeGdM commented on Gazebo/WhatIs.md
> +Vamos entender cada comando?
```suggestion
Vamos entender cada parte do comando?
```

2021-04-16 16:19 UTC, FelipeGdM commented on Gazebo/WhatIs.md
> +Aqui, você está se referenciando ao arquivo de *launch* que irá gerar o mundo.
```suggestion
Aqui, você está se referindo ao arquivo de *launch* que irá gerar o mundo.
```

Aqui pode ser "se referindo" ou "referenciando"

2021-04-16 16:19 UTC, FelipeGdM commented on Gazebo/WhatIs.md
> +Aqui, você está se referindo ao nome do pacote. Você pode ler mais sobre pacotes [**neste link**](http://wiki.ros.org/Packages). Em resumo, um software do ROS é organizado em pacotes, e cada pacote c
```suggestion
Aqui, você está se referindo ao nome do pacote. Falamos um pouco sobre pacotes no no guida de instalação do ROS e você pode ler mais sobre pacotes no contexto de ROS [**neste link**](http://wiki.ros.org/Packages). Em resumo, um software do ROS é organizado em pacotes, e cada pacote contém *nodes*, livrarias e softwares externos.
```

2021-04-18 18:05 UTC, LucasHaug requested changes

2021-04-18 18:05 UTC, LucasHaug commented on Gazebo/WhatIs.md
> +Aqui, você está se referindo ao nome do pacote. Falamos um pouco sobre pacotes no no guida de instalação do ROS e você pode ler mais sobre pacotes no contexto de ROS [**neste link**](http://wiki.ros.
```suggestion
Aqui, você está se referindo ao nome do pacote. Falamos um pouco sobre pacotes no guia de instalação do ROS e você pode ler mais sobre pacotes no contexto de ROS [**neste link**](http://wiki.ros.org/Packages). Em resumo, um software do ROS é organizado em pacotes, e cada pacote contém *nodes*, bibliotecas e softwares externos.
```

2021-04-18 18:05 UTC, LucasHaug commented on Gazebo/WhatIs.md
> +Aqui, você está se referindo ao arquivo de *launch* que irá gerar o mundo.
```suggestion
Aqui, você está se referindo ao arquivo de *launch* que irá carregar o mundo.
```

2021-04-19 22:02 UTC, mariarezende07 commented on Gazebo/WhatIs.md
> +Com todas essas funcionalidades que as simulações proporcionam, o projeto final terá um comportamento próximo do desejado quando for colocado no ambiente real. Além de saber isso sem precisar constru
Eu tentei resolver adicionando um parenteses, mas não sei se foi suficiente

2021-04-19 23:13 UTC, febagni approved these changes
Do que eu tinha pedido está check!

2021-04-20 00:46 UTC, lucas-pvg commented on Gazebo/WhatIs.md
> +![Logo do Gazebo](../assets/img/gazebo/gazebologo.png){: .d-block .mx-auto}
Oi gnt :3
Eu sei que tem vários flavors de markdown e eu mesmo já tive problemas com a visualização do github desse tipo d arquivo, mas em tdas as imagens a linha `{: .d-block .mx-auto}` fica aparecendo. ~~n sei oq ela significa rsrs, mas vale a pena avisar~~ SZ

2021-04-20 00:46 UTC, lucas-pvg approved these changes

2021-04-20 00:53 UTC, mariarezende07 commented on Gazebo/WhatIs.md
> +![Logo do Gazebo](../assets/img/gazebo/gazebologo.png){: .d-block .mx-auto}
Então, ele serve pra centralizar as imagens. Pelo que eu entendi, ele aparece aqui mas some quando colocado no site, similar a [essa outra documentação](https://github.com/ThundeRatz/ROSGazeboGuide/blob/main/ROS/WhyToUse.md).

2021-04-20 01:02 UTC, LucasHaug approved these changes

2021-04-20 01:03 UTC, merged