Documentação "O que é ROS?"
ThundeRatz/ROSGazeboGuide pull request #17
Opened 2021-04-09 17:07 UTC by leticiakimoto

Oi, pessoal!
Nesse texto explico o que é ROS e seus conceitos básicos

2021-04-09 17:34 UTC, GabrielKishida reviewed
Opa, belo PR!
Vim aqui dar alguns pitacos:
Acho que a ideia geral está bem legal, só precisa dar uma "almofadada" nas coisas pois as pessoas que vão ler isso tem muito menos conhecimento base do que a gente, então é importante adaptar de uma maneira didática esse conhecimento para pessoas "leigas".

Dito isso, acredito que as coisas estejam caminhando para um caminho legal. Boa, @leticiakimoto !

2021-04-09 17:34 UTC, GabrielKishida commented on ROS/WhatIs.md
> +O ROS (Robot Operating System) é um framework para desenvolvimento, reuso e compartilhamento de software no contexto de robótica.
Eu gosto bastante dessa frase, acho que ela é bem objetiva e sucinta na descrição do ROS.
No entanto, acredito que ela seja um pouco objetiva demais para pessoas que desconhecem ROS e o mundo de computação/engenharia. Na minha opinião fica um pouco vago para a pessoa comum o que essas palavras significam.

Talvez dar um exemplo de uso, ou algum comentário que interesse mais o aluno (tentar atrair o aluno com gifs tipo, olha o que conseguimos fazer com ROS, ou coisas do tipo) , que o faça querer aprender mais sobre.

2021-04-09 17:34 UTC, GabrielKishida commented on ROS/WhatIs.md
> +Framework é um conjunto de bibliotecas e estruturas padronizadas que podem ser reutilizadas em diferentes processos. Ou seja, sua principal função é resolver os problemas frequentes, por meio de uma
Acho que dá para colocar alguns exemplos de Framework conhecidos -- tipo Unity ou coisas de conhecimento comum
(esse comentário meu é meio banana, se você acredita que não precisa pode ignorar o que eu disse)

2021-04-09 17:34 UTC, GabrielKishida commented on ROS/WhatIs.md
> +Canal de comunicação entre nodes e identifica o conteúdo da message.
Acho que esse meu comentário vale não só para os Tópicos, mas também para os Nodes e para os Messages.

Sinto que seria interessante e ajudaria o aluno entender a aplicação do ROS se você colocasse junto com o texto um exemplo de Node, de Topic e de Message.
Usando, por exemplo, um sensor de linha, onde o tópico é o canal de comunicação, a leitura do sensor é a mensagem transmitida pelo tópico, e essa mensagem é processada pelos nodes... Algo assim, sabe?
Acho que contar uma historinha concreta da aplicação desses conceitos abstratos ajudaria bastante o aluno comum -- imagino que eu entenderia melhor essas coisas da primeira vez se houvesse um contexto que eu pudesse entender por trás.

2021-04-09 17:34 UTC, GabrielKishida commented on ROS/WhatIs.md
> +
Acho que dá para colocar um Índice aqui, ou pelo menos um link para o "why use" do ROS para integrar melhor o documento com o resto do tutorial.

2021-04-10 03:43 UTC, febagni requested changes
Ótima documentação e explicações, as sugestões de modificações fui deixando como comentários ! Excelente trabalho!

2021-04-10 03:43 UTC, febagni commented on ROS/WhatIs.md
> +
Concordo, acho que facilita bastante a navegação, acho que fizemos um no [Docker tutorial de mac](https://github.com/ThundeRatz/ROSGazeboGuide/blob/docker_tutorial/InstalationGuides/DockerMac.md), aí é só seguir o msm esquema :smile:

2021-04-10 03:43 UTC, febagni commented on ROS/WhatIs.md
> +O ROS (Robot Operating System) é um framework para desenvolvimento, reuso e compartilhamento de software no contexto de robótica.
Acho que um exemplo sempre ajuda a entender os conceitos mais complicados e uma outra coisa, não faz mais sentido inverter a ordem e introduzir os conceito de framework antes de definir ROS?

2021-04-10 03:43 UTC, febagni commented on ROS/WhatIs.md
> +Canal de comunicação entre nodes e identifica o conteúdo da message.
Meu comentário aqui seria colocar esses conceitos como tópicos, mais pra facilitar a leitura msm :smile:

2021-04-17 16:53 UTC, mariarezende07 requested changes

2021-04-17 16:53 UTC, mariarezende07 commented on ROS/WhatIs.md
> +O ROS (Robot Operating System) é um framework para desenvolvimento, reuso e compartilhamento de software no contexto de robótica.
Concordo com as opiniões acima de colocar um exemplo, talvez colocar algo tipo "imagine que você está em tal situação com seu grupo e precisa fazer tal tal coisa, é aí que o ROS vai te auxiliar"

2021-04-17 16:53 UTC, mariarezende07 commented on ROS/WhatIs.md
> +Nesta parte serão explicados alguns conceitos básicos do ROS.
Eu sou meio chatoncia pra coisa de texto, mas eu acho que talvez dar um panorama geral dos conceitos fosse algo legal

2021-04-17 16:53 UTC, mariarezende07 commented on ROS/WhatIs.md
> +Canal de comunicação entre nodes e identifica o conteúdo da message.
Vou acrescentar que eu acho que seria legal também colocar um link da wiki de ros para cada tópico

2021-04-17 16:53 UTC, mariarezende07 commented on ROS/WhatIs.md
> +
Acho que seria legal colocar aqui um textinho explicando a imagem que vem abaixo, mais pra finalizar direitinho

2021-04-20 00:24 UTC, febagni commented on ROS/WhatIs.md
> +- Maior consistência das aplicações
```suggestion
Bem, eles permitem algumas vantagens, como:

- Redução na incidência de bugs;
- Padronização de códigos;
- Redução de custos operacionais;
- Maior consistência das aplicações.
```

2021-04-20 00:27 UTC, febagni commented on ROS/WhatIs.md
> +Explicando a imagem:
Não entendi isso

2021-04-20 00:28 UTC, febagni commented on ROS/WhatIs.md
> +Explicando a imagem:
Vem dps as referências já?

2021-04-20 00:28 UTC, mariarezende07 commented on ROS/WhatIs.md
> +Explicando a imagem:
calma

2021-04-20 00:28 UTC, leticiakimoto commented on ROS/WhatIs.md
> +Explicando a imagem:
ainda n tinhamos explicado kkkk, na proxima vai completo

2021-04-20 00:42 UTC, febagni submitted a review, later dismissed
Ótimo trabalho! Me parece tudo check!

2021-04-20 00:42 UTC, febagni commented on ROS/WhatIs.md
> +Explicando a imagem:
justo ausdhuashda vi agr e já aprovei :smile:

2021-04-20 00:56 UTC, GabrielCosme reviewed
Acho que não faz parte desse PR especificamente, mas na parte de instalação, já que a ideia é ser bem básico, talvez seria bom avisar que depois de digitar o sudo ele vai pedir a senha, e quando estiver digitando a senha não vai aparecer no terminal, acredito que é algo que as pessoas costumam se confundir.

2021-04-20 01:01 UTC, GabrielKishida requested changes
Bom gente, desculpa ser um pouco 1 pé no saco mas eu ainda acho que dá pra dar uma digerida. O texto está bem bom e bem didático mas ele é um pouco intimidador.

Entao, dei uma sugestao do o que pode ser feito. (nao me odeiem)

2021-04-20 01:01 UTC, GabrielKishida commented on ROS/WhatIs.md
> +Forma de comunicação entre nodes. A message possui dados que fornecem informações para outros nodes. Para saber mais detalhadamente sobre o que são messages, dê uma olhada na Wiki oficial do ROS, dis
Gostei de como ficaram esses tópicos, ficou bem atômico e fácil de ler, entao ficou bem enxuto.

Só acho que seria ideal se desse aquela almofadada nesses exemplos aqui também. Algo do tipo:

```suggestion
### **Message**

Forma de comunicação entre nodes. A message possui dados que fornecem informações para outros nodes. 
Um exemplo prático de *message* seria a leitura de um sensor de distância. Essas mensagens poderiam ser valores de distância, como 140 (cm), por exemplo. Dessa forma o sensor se comunica com os outros nodes.
Para saber mais detalhadamente sobre o que são messages, dê uma olhada na Wiki oficial do ROS, disponível [**nesse link**](http://wiki.ros.org/msg).
```

2021-04-20 01:10 UTC, mariarezende07 submitted a review, later dismissed
Pra mim ta tudo check agora, toop

2021-04-20 01:14 UTC, GabrielKishida reviewed
Entao, eu comentei aquela coisa sobre o tópico da mensagem (falando pra "almofadar" com um exemplo) mas eu tava pensando em fazer isso pra cada tópico (node, package, message, topico). Eu tinha dado o exemplo no "message" mas seria legal se tivesse um pra cada tópico.

Isso é só minha opiniao também nao precisa seguir se achar desnecessário

2021-04-20 01:14 UTC, GabrielKishida commented on ROS/WhatIs.md
> +### **Tópico**
Como tá tudo em inglês, acho que faz mais sentido ficar esse aqui em inglês também.

```suggestion
### **Topic**
```

2021-04-20 02:06 UTC, DamaralHenrique reviewed
Achei o texto muito bom e didático! Acredito que o exemplo final vai ajudar bastante os bixos, considerando que esta será o primeiro contato deles com o ROS. 
Só acho válido comentar pra não esquecer de retirar a tabela de estilos que está no início dos arquivos `WhatIs.md` e `README.md`.

2021-04-20 02:11 UTC, guedeslucas1 commented on ROS/WhatIs.md
> +<img src="../assets/img/ROSGazebo/ros-example.png" alt="ROS_example" height="655" width="925" style ="margin:auto; display:block">
Eu acho esse exemplo muito legal, porém pessoalmente acho que como quem está lendo acabou de ter contato com esses conceitos de message, topic e etc talvez seria interessante uma coisa mais simples e que mostrasse pra ele que conceitualmente o que ele entendeu está correto, antes de partir para um exemplo prático, como [isso aqui](https://www.designnews.com/sites/designnews.com/files/Design%20News/ROS_System_Model_0.jpg). Mas gosto desse exemplo no fim do tutorial!

2021-04-20 02:41 UTC, LucasHaug requested changes

2021-04-20 02:41 UTC, LucasHaug commented on ROS/WhatIs.md
> +- [**O que é ROS?**](#O-que-é-ROS?)
```suggestion

- [**O que é ROS?**](#O-que-é-ROS?)
```

2021-04-20 02:41 UTC, LucasHaug commented on InstalationGuides/ROSGazeboUbuntu.md
> +
```suggestion

- [**Observações Iniciais**](#observações-iniciais)
- [**Pré-requisitos**](#pré-requisitos)
- [**Instalação do Docker Desktop**](#instalação-do-docker-desktop)
- [**Possível erro**](#possível-erro)
- [**Verificação**](#verificação)
- [**Observações Finais**](#observações-finais)
- [**Para saber mais**](#para-saber-mais)
```

2021-04-20 02:45 UTC, LucasHaug commented on ROS/WhatIs.md
> +<img src="../assets/img/ros_logo.png" alt="ROS_logo" height="341" width="1280" style ="margin:auto; display:block">
```suggestion
<img src="../assets/img/ros_logo.png" alt="ROS_logo" height="341" width="auto" style ="margin:auto; display:block">
```

2021-04-20 02:48 UTC, LucasHaug approved these changes

2021-04-20 02:48 UTC, merged