Índice dos Guias de Instalação
ThundeRatz/ROSGazeboGuide pull request #19
Opened 2021-04-23 19:48 UTC by GabrielKishida

Oi gente!
Mais uma PR, eu sei... mas essa daqui deve ser rapidinha.

Preparei o índice para os guias de instalação. Acho que tá tudo dentro dos conformes --  a única coisa que eu acho um pouco controversa é o índice no meio do texto. Não sei muito onde jogar ele, pq acho que no final fica meio perdido, e no começo fica meio estranho também.

Enchi a coisa de negrito e de links pra ser quase impossível a pessoa não saber para onde ir.

2021-04-24 11:07 UTC, Drebt requested changes

2021-04-24 11:07 UTC, Drebt commented on InstalationGuides/README.md
> +Se você ainda não sabe muito bem o que é ROS, nem para o que serve, recomendamos ler a **[seção do Gazebo](../Gazebo/README.md)**. Por outro lado, se suas dúvidas são sobre o que é ROS e suas utilida
Acho que aqui o copy-paste falou e deixou um ROS onde deveria ser o Gazebo

```suggestion
Se você ainda não sabe muito bem o que é Gazebo, nem para o que serve, recomendamos ler a **[seção do Gazebo](../Gazebo/README.md)**. Por outro lado, se suas dúvidas são sobre o que é ROS e suas utilidades, sugerimos a **[seção do ROS](../ROS/README.md)**
```

2021-04-26 00:14 UTC, FelipeGdM approved these changes
Show de boleta, é isso aí msm

2021-04-26 23:39 UTC, mariarezende07 requested changes
Só um request changes aqui pq a PR da instalação do Docker ainda não foi fechada, mas é importante colocar aqui tmb

2021-04-30 03:10 UTC, febagni commented
Acho que tá tudo certo, só fica essa pendência que a @mariarezende07 falou sobre os arquivos de instalação do Docker

2021-05-05 19:10 UTC, mariarezende07 submitted a review, later dismissed
Como os negócios do Docker ficaram pra dps, vim dar approve. Topp

2021-05-07 11:50 UTC, VanderSant requested changes
Toop, esse index realmente iria fazer muita falta! mandou muito.
No geral, eu iria preferir mantem o X server como subtópico do "ROS/Gazebo Para WSL". Tirando isso, pra mim está perfeito.

2021-05-07 16:41 UTC, LucasHaug requested changes
Comentei só coisa bobinha, mas tá bem toppp

2021-05-07 16:41 UTC, LucasHaug commented on InstalationGuides/README.md
> +
```suggestion
```

2021-05-07 16:41 UTC, LucasHaug commented on InstalationGuides/README.md
> +- [Github Desktop](./UsingGithubDesktop.md)
Acho que dá talvez pra gente arrumar as coisas pra serem subtópicos mesmo, fazer tipo uma pasta Windows e uma Ubuntu e tals, mas acho que isso melhor fazer depois, porque vai mudar a posição de muitas coisas, então melhor ter dado merge de tudo antes de fazer essas coisas.

2021-05-07 16:41 UTC, LucasHaug commented on InstalationGuides/README.md
> +Se você está iniciando o desenvolvimento do seu projeto no **Windows**, será bem útil aprender a **[instalar o WSL](./WSL.md)**, dado que grande parte dos programas usará esse sistema.
```suggestion
Se você está iniciando o desenvolvimento do seu projeto no **Windows**, será bem útil aprender a **[instalar o WSL](./WSL.md)**, dado que grande parte dos programas usará esse subsistema.
```

2021-05-07 16:41 UTC, LucasHaug commented on InstalationGuides/README.md
> +Por fim, se você quer aprender como instalar e usar uma ferramenta que facilita muito o trabalho em equipe em um contexto à distância, leia o guia de **[como usar e instalar o Github Desktop](UsingGi
```suggestion

Por fim, se você quer aprender como instalar e usar uma ferramenta que facilita muito o trabalho em equipe em um contexto à distância, leia o guia de **[como usar e instalar o Github Desktop](UsingGithubDesktop.md)**!
```

2021-05-20 14:34 UTC, VanderSant commented on InstalationGuides/README.md
> +Por fim, se você quer aprender como instalar e usar uma ferramenta que facilita muito o trabalho em equipe em um contexto à distância, leia o guia de **[como usar e instalar o Github Desktop](UsingGi
@GabrielKishida 👀

2021-05-20 14:34 UTC, VanderSant commented
@GabrielKishida 👀

2021-05-20 22:28 UTC, GabrielKishida commented
Desculpa o atraso time, por causa do trabalho as PRs encheram e essa aqui ficou lá pra baixo, acabei não vendo.

2021-05-20 23:41 UTC, LucasHaug approved these changes

2021-05-21 11:44 UTC, VanderSant approved these changes

2021-05-21 12:20 UTC, GabrielKishida commented
@Drebt senpai, preciso do seu approval

2021-05-27 17:29 UTC, febagni approved these changes
:white_check_mark:

2021-05-27 18:33 UTC, Drebt approved these changes

2021-05-27 18:38 UTC, merged