Feature/why to use simulation
ThundeRatz/ROSGazeboGuide pull request #20
Opened 2021-04-24 18:54 UTC by wulcao

Oi, galera! Adicionei (a Letícia, na verdade) o texto sobre "Por que usar uma ferramenta de simulação?". Espero que gostem!

2021-04-26 23:47 UTC, mariarezende07 requested changes

2021-04-26 23:47 UTC, mariarezende07 commented on Gazebo/WhyToUseSimulationTools.md
> +Existem diversos tipos de simulação, seja na área da mecânica e até mesmo no setor financeiro, mas todos têm algo em comum: a possibilidade de realizar testes prévios de modo virtual antes do projeto
```suggestion
 Por exemplo, é mais viável realizar uma simulação de uma hélice de usina eólica do que precisar modificar a hélice já construida, tendo que refazê-la, após erros que poderiam ter sido previstos com simulação.
```

2021-04-26 23:47 UTC, mariarezende07 commented on Gazebo/WhyToUseSimulationTools.md
> +Analisando o papel do ROS e do Gazebo no projeto de carrinho seguidor de linha, é possível analisar se as dimensões estão adequadas ao tamanho da pista, bem como às curvaturas presentes na mesma, e s
Acho que essa parte pode ser mais desenvolvida. É legal citar mais sobre como simuladores como o Gazebo e o Rviz podem ajudar, adicionar alguma imagem de exemplo e coisa do tipo.

2021-05-05 17:44 UTC, FelipeGdM reviewed
Achei bem daora o paralelo com mecânica, era isso mesmo que eu tinha em mente!

Tem alguns disclaimers ~a voz da experiência~ que são bons de serem colocados no meio/final, nas palavras da profa. Larissa

> O computador pode tornar excelente um bom engenheiro, mas podem tornar perigoso um mau engenheiro

Concordo com a @mariarezende07, acredito que dá pra explorar mais o papel de Gazebo/Rviz na nossa brincadeira. Vou pegar essa extensão pra fazer, acredito que o Wu teria dificuldade para

No mais, show de bola o trabalho

2021-05-05 17:44 UTC, FelipeGdM commented on Gazebo/WhyToUseSimulationTools.md
> +Existem diversos tipos de simulação, seja na área da mecânica e até mesmo no setor financeiro, mas todos têm algo em comum: a possibilidade de realizar testes prévios de modo virtual antes do projeto
```suggestion
Existem diversos tipos de simulação, seja na engenharia mecânica, elétrica ou até mesmo no setor financeiro, mas todas têm algo em comum: a possibilidade de realizar testes prévios de modo virtual antes do projeto real ser feito. Esse aspecto é muito importante porque permite a tomada de decisões antes que recursos sejam gastos com a fabricação de um protótipo. Por exemplo, é mais barato realizar uma alteração de projeto em uma hélice de usina eólica durante a fase de simulação do que após sua fabricação.
```

2021-05-05 17:44 UTC, FelipeGdM commented on Gazebo/WhyToUseSimulationTools.md
> +No caso da mecânica, programas do tipo CAE (Computer-aided engineering), como Abaqus e Ansys, são muito utilizados para analisar o estresse, a deformação, a transferência de calor, a distribuição do
```suggestion
No campo da engenharia mecânica, programas do tipo CAE (Computer-aided engineering) (e.g. Abaqus e Ansys), são muito utilizados para analisar diferentes características de uma peça em regime de trabalho, como o estresse, a deformação, a transferência de calor ou mesmo a distribuição do campo magnético.
```

2021-05-05 17:44 UTC, FelipeGdM commented on Gazebo/WhyToUseSimulationTools.md
> +Tomando a imagem a seguir como exemplo, é possível ver os níveis de deformação plástica destacados pela cor, sendo que na parte onde está cinza possui alta chance de quebrar e as partes azuis represe
```suggestion
Tomando a imagem a seguir como exemplo, é possível ver os níveis de deformação plástica de uma peça mediante impacto. Os resultados são destacados pela cor, sendo que a parte cinza possui maior chance de quebrar e as partes azuis representam as regiões menos afetadas. Dessa forma, podemos analisar qual o comportamento esperado para a peça antes mesmo que ela seja fabricada, de modo que podemos reforçar regiões mais afetadas ou mesmo retirar material das partes menos afetadas
```

2021-05-07 18:18 UTC, LucasHaug requested changes

2021-05-07 18:18 UTC, LucasHaug commented on Gazebo/WhyToUseSimulationTools.md
> + Por exemplo, é mais viável realizar uma simulação de uma hélice de usina eólica do que precisar modificar a hélice já construida, tendo que refazê-la, após erros que poderiam ter sido previstos com
Acho que dá pra fazer uma introduçãozinha antes de já começar a falar "por exemplo"

2021-05-07 18:18 UTC, LucasHaug commented on Gazebo/WhyToUseSimulationTools.md
> +Analisando o papel do ROS e do Gazebo no projeto de carrinho seguidor de linha, é possível analisar se as dimensões estão adequadas ao tamanho da pista, bem como às curvaturas presentes na mesma, e s
> Acho que essa parte pode ser mais desenvolvida. É legal citar mais sobre como simuladores como o Gazebo e o Rviz podem ajudar, adicionar alguma imagem de exemplo e coisa do tipo.

Concordo também

2021-05-20 23:18 UTC, VanderSant requested changes
Não tenho muito o que falar. Em geral está bom

2021-05-20 23:18 UTC, VanderSant commented on Gazebo/WhyToUse.md
> +Como nem tudo são flores, o bom uso de um software de simulação exige grande discernimento da passoa que o utiliza. O computador não sabe distinguir entre entradas absurdas de razoáveis e para qualqu
```suggestion
Como nem tudo são flores, o bom uso de um software de simulação exige grande discernimento da pessoa que o utiliza. O computador não sabe distinguir entre entradas absurdas de razoáveis e para qualquer entrada ele irá produzir uma resposta. É trabalho da engenheira ou do engenheiro responsável analisar de modo crítico os dados que entram e saem da simulação. Aqui, aplica-se o mesmo princípio vigente em estatística "entra lixo, sai lixo".
```

2021-05-27 17:44 UTC, febagni commented on Gazebo/WhyToUse.md
> +Existem diversos tipos de simulação, seja na engenharia mecânica, elétrica ou até mesmo no setor financeiro, mas todas têm algo em comum: a possibilidade de realizar testes prévios de modo virtual an
```suggestion
Existem diversos tipos de simulação, seja na engenharia mecânica, elétrica ou até mesmo no setor financeiro, mas todas têm algo em comum: a possibilidade de realizar testes prévios de modo virtual antes do projeto real ser feito. Simulações virtuais são uma ferramenta extremamente poderosa, pois permitem a tomada de decisões e mudanças no projeto antes que recursos sejam gastos com a fabricação de um protótipo. Por exemplo, é mais barato realizar uma alteração de projeto em uma hélice de usina eólica durante a fase de simulação do que após sua fabricação.
```

2021-05-27 17:49 UTC, febagni commented on Gazebo/WhyToUse.md
> +> A ferramenta de simulação numérica torna excelente o bom engenheiro, mas torna perigoso o mal engenheiro
```suggestion
> A ferramenta de simulação numérica torna excelente o bom engenheiro, mas torna perigoso o mal engenheiro.
```

2021-05-27 17:50 UTC, febagni commented on Gazebo/WhyToUse.md
> +Se mal aplicada, uma simulação pode fornecer uma falsa sensação de segurança ao profissional descuidado e levar a falhas de projeto catastróficas. A todo momento é importante se questionar "O resulta
```suggestion
Se mal aplicada, uma simulação pode fornecer uma falsa sensação de segurança ao profissional descuidado e levar a falhas de projeto catastróficas. A todo momento é importante se questionar "O resultado da simulação é condizente com a teoria?" ou "O resultado da simulação é condizente com resultados anteriores?", de modo que a simulação não acabe com a necessidade do domínio metodológico da teoria dos processos envolvidos.
```

2021-06-23 16:36 UTC, mariarezende07 approved these changes

2021-06-23 16:40 UTC, LucasHaug approved these changes

2021-06-24 16:42 UTC, VanderSant approved these changes

2021-06-24 18:38 UTC, merged