Add índice para as páginas How to run
ThundeRatz/ROSGazeboGuide pull request #21
Opened 2021-04-26 00:18 UTC by FelipeGdM

Salve salve garotada

Conforme o nosso planejamento, cá estou com o índice para as páginas How to run. Kibei na cara dura o trabalho :top: do @GabrielKishida na PR #19, de modo a manter um mesmo padrão de conteúdo

Foi uma mudança pequena, estamos na reta final do projeto

No mais, fiquem bem e mantenham-se hidratados

2021-04-26 23:41 UTC, mariarezende07 requested changes
Mesmo comentário que eu fiz na PR do @GabrielKishida sobre colocar sobre o Docker. Também acho uma boa pensar em colocar os de Mac

2021-05-05 19:10 UTC, mariarezende07 approved these changes
Como os negócios do Docker ficaram pra dps, vim dar approve. Topp

2021-05-05 19:31 UTC, GabrielKishida requested changes
Acho que só isso, não vi nada a mais para mudar.
Show de bola!

2021-05-05 19:31 UTC, GabrielKishida commented on HowToRun/README.md
> +- [Como exeutar o projeto no Ubuntu](./RunOnUbuntu.md)
```suggestion
- [Como executar o projeto no Windows](./RunOnWSL.md)
- [Como executar o projeto no Ubuntu](./RunOnUbuntu.md)
```

2021-05-05 21:22 UTC, GabrielKishida approved these changes
Acho que agora tá clean!
:partying_face:

2021-05-05 21:28 UTC, GabrielKishida approved these changes
Desculpa o bait do approve, mas eu acabei de ver que esse trecho nao estava em negrito.

Mesmo assim, acho que já vou deixar approved pois eu acho que é um detalhe bem pequeno e nao quero engessar o merge.

2021-05-05 21:28 UTC, GabrielKishida commented on HowToRun/README.md
> +Caso você já saiba o que é o ROS e o Gazebo mas ainda não tenha instalado os programas e bibliotecas no seu computador, recomendo que você veja a [seção de como instalar ROS e Gazebo](../InstalationG
```suggestion
Caso você já saiba o que é o ROS e o Gazebo mas ainda não tenha instalado os programas e bibliotecas no seu computador, recomendo que você veja a **[seção de como instalar ROS e Gazebo](../InstalationGuides/README.md)** antes de continuar aqui
```

2021-05-07 12:04 UTC, VanderSant requested changes
~Desculpa floodar hasuahsua~
Ficou bem top, Felipe.

2021-05-07 12:04 UTC, VanderSant commented on HowToRun/README.md
> +Se você ainda não sabe muito bem o que é Gazebo, nem para o que serve, recomendamos ler a **[seção do Gazebo](../Gazebo/README.md)**. Por outro lado, se suas dúvidas são sobre o que é ROS e suas util
```suggestion
Se você ainda não sabe muito bem o que é Gazebo, nem para o que serve, recomendamos ler a **[seção do Gazebo](../Gazebo/README.md)**. Por outro lado, se suas dúvidas são sobre o que é ROS e suas utilidades, sugerimos a **[seção do ROS](../ROS/README.md)**.
```

2021-05-07 12:04 UTC, VanderSant commented on HowToRun/README.md
> +Caso você já saiba o que é o ROS e o Gazebo mas ainda não tenha instalado os programas e bibliotecas no seu computador, recomendo que você veja a [seção de como instalar ROS e Gazebo](../InstalationG
```suggestion
Caso você já saiba o que é o ROS e o Gazebo mas ainda não tenha instalado os programas e bibliotecas no seu computador, recomendo que você veja a [seção de como instalar ROS e Gazebo](../InstalationGuides/README.md) antes de continuar aqui.
```

2021-05-07 12:04 UTC, VanderSant commented on HowToRun/README.md
> +Caso você utilize o **Windows** como sistema operacional, [clique aqui](./RunOnWSL.md)
```suggestion
Caso você utilize o **Windows** como sistema operacional, [clique aqui](./RunOnWSL.md).
```

2021-05-07 12:04 UTC, VanderSant commented on HowToRun/README.md
> +Caso você utilize o **Ubuntu** como sistema operacional, [clique aqui](./RunOnUbuntu.md)
```suggestion
Caso você utilize o **Ubuntu** como sistema operacional, [clique aqui](./RunOnUbuntu.md).
```

2021-05-07 16:45 UTC, LucasHaug approved these changes

2021-05-10 14:43 UTC, LucasHaug approved these changes

2021-05-10 15:25 UTC, merged