Dev/instalation guides ros gazebo
ThundeRatz/ROSGazeboGuide pull request #3
Opened 2021-03-18 13:39 UTC by GabrielKishida

Estou fazendo esse PR para que a equipe possa revisar e comentar mudanças antes de juntar a branch com a main.

2021-03-18 15:33 UTC, LucasHaug commented on InstalationGuides/ROSGazebo.md
> +
Acho que seria legal colocar um índice aqui.

2021-03-18 15:33 UTC, LucasHaug commented on InstalationGuides/ROSGazebo.md
> +Para continuar, basta escrever **y** e apertar Enter.
Podem deixar desse jeito aí mesmo acho melhor, mas só comentando que ali como é Y maiúsculo, o Yes é o padrão, então se você só der enter funciona.

2021-03-18 15:33 UTC, LucasHaug commented on InstalationGuides/ROSGazebo.md
> +![Opening CMD](/assets/img/ROSGazebo/opencmd.png)
Então não usou o cmd na parte do WSL né? ahhahahahasusahas

2021-03-18 15:33 UTC, LucasHaug commented on InstalationGuides/ROSGazebo.md
> +![Opening CMD](/assets/img/ROSGazebo/add_repository.png)
O nome da imagem ficou "Opening CMD" shuashauhsaushauhs

2021-03-18 15:33 UTC, LucasHaug commented on InstalationGuides/ROSGazebo.md
> +É importante que você defina a "source" deste script em todo terminal **bash** que você usa ROS.
Então acho que aqui seria mais falar acho "configurar o ambiente do terminal", pra que as coisas do ROS sejam achadas no seu computador. O `source` basicamente executa o script na shell que você tá, isso é importante pra que as configurações fiquem no seu terminal, se você rodasse o script só com o nome dele e não com o `source`, você iria rodar num shell filho e as configurações não estariam no shell que você tá.

2021-03-18 15:33 UTC, LucasHaug commented on InstalationGuides/ROSGazebo.md
> +Feito isso, vamos instalar o pacote do ROS. **Precisamos** instalar o pacote **"desktop-full"** para instalar os adendos responsáveis por simulação 2D/3D -- como o *Gazebo* -- senão faltará coisas na
```suggestion
Feito isso, vamos instalar o pacote do ROS. **Precisamos** instalar o pacote **"desktop-full"** para instalar os adendos responsáveis por simulação 2D/3D -- como o *Gazebo* -- senão faltarão pacotes na máquina. Assim, o comando é:
```

2021-03-18 15:33 UTC, LucasHaug commented on InstalationGuides/ROSGazebo.md
> +Feito isso, vamos instalar o pacote do ROS. **Precisamos** instalar o pacote **"desktop-full"** para instalar os adendos responsáveis por simulação 2D/3D -- como o *Gazebo* -- senão faltará coisas na
```suggestion
Feito isso, vamos instalar o pacote do ROS. **Precisamos** instalar o pacote **"desktop-full"** para instalar os adendos responsáveis por simulação 2D/3D -- como o *Gazebo* -- senão faltarão pacotes na máquina. Assim, o comando é:
```

2021-03-18 15:33 UTC, LucasHaug commented on InstalationGuides/ROSGazebo.md
> +
Eu acho que tiraria esse vídeo, como ele não é nosso acho melhor deixar só as nossas coisas.

2021-03-18 15:33 UTC, LucasHaug commented on InstalationGuides/ROSGazebo.md
> +<img src="https://lh3.googleusercontent.com/pw/ACtC-3d1hybWo5Ee3nwj01Vk_NElno6nyDpEgMNFz5WN_AKVfxd_6ImQZFt4iVdGHDOqAvFGOQa5KpMoMO7OlKEuW5_51D-NsbIa9r_A-7UrBLxv5U_KuDJfhrUizCOUk6cqAr5Ve1U6P07r775GQOqH
Nossa onde que essas imagens tão?? hsuahsuhasuhuashusah pode por no repo mesmo acho

2021-03-18 15:33 UTC, LucasHaug commented on InstalationGuides/ROSGazebo.md
> +![Checking Gazebo](/assets/gif/ROSGazebo/gazebo-version.gif)
Acho que aqui e em outros lugares mais pra baixo eu só daria um espaço entre o texto e o gif ahsuhaushaushuahsuh

2021-03-18 16:19 UTC, FelipeGdM commented on InstalationGuides/ROSGazebo.md
> +![ROS Logo](/assets/img/thunder_ros.png)
Não precisa ser nessa PR

2021-03-18 16:21 UTC, FelipeGdM commented on InstalationGuides/ROSGazebo.md
> +![Opening CMD](/assets/img/ROSGazebo/opencmd.png)
Nuss, pode pá, eu tb nem me toquei. O tutorial inteiro vc tá usando o terminal do WSL, né? Não o terminal do Windows

2021-03-18 16:22 UTC, FelipeGdM commented on InstalationGuides/ROSGazebo.md
> +É importante que você defina a "source" deste script em todo terminal **bash** que você usa ROS.
Acho que só um "Configurar o terminal" é suficiente

2021-03-18 16:37 UTC, GabrielKishida commented on InstalationGuides/ROSGazebo.md
> +![Opening CMD](/assets/img/ROSGazebo/add_repository.png)
Oops

2021-03-18 16:47 UTC, d-nery commented
~~pablinho-KISHIDAS-pc~~

2021-03-18 17:04 UTC, LucasHaug commented on InstalationGuides/ROSGazebo.md
> +![ROS Logo](/assets/img/thunder_ros.png)
Ah mas acho que também se ela tá no README principal não precisa repetir aqui, aí o do README principal acho de boas tirar depois mesmo

2021-03-18 18:37 UTC, GabrielKishida commented
Pessoal, fiz umas mudanças de acordo com o que pediram. Deixei o vídeo e os links das imagens pois elas são de autoria do @VanderSant e queria deixar ao critério dele. De resto, mais alguém tem alguma sugestão de mudança?

2021-03-18 19:08 UTC, LucasHaug commented on InstalationGuides/ROSGazeboUbuntu.md
> +![Repositories Table](/assets/img/ROSGazebo/repositories.png)
Acho que dá pra colocar uma tabela direto ao invés de uma imagem, tipo:

Exemplo | Exemplo 2
----------| ------------
Cenoura | Check
Batata    | Check
Azul       | Não Check


Nesse `.md` e no outro.

2021-03-18 19:08 UTC, LucasHaug commented on InstalationGuides/ROSGazeboUbuntu.md
> +É importante que você defina a "source" deste script em todo terminal **bash** que você usa ROS.
Faltou arrumar essa frase lá, falar "configurar o terminal" ao invés de "definir a source". Nesse `.md` e no outro.

2021-03-19 15:32 UTC, LucasHaug reviewed
Vou fazer um comentário geral porque tem em vários lugares, acho que dá pra tirar as coisas em html, acho que não precisa daqueles `<br>` e daqueles `<div>` . Outra coisa, em muitos lugares tem um "---" (ou com mais hífens hahahahah), dá pra tirar esses também, os próprios títulos já tem uma linha em baixo mais fina. E uma outra coisa pro do WSL, acho que dá pra fazer que nem o do Ubuntu fez nesse commit f7f3655ac4082f37181f72a34c446163a058226a com os títulos.

2021-03-19 15:48 UTC, lucastrschneider requested changes
Muito bom galera!
O conteúdo ta sensacional, só fiz uns comentários com alguns ajustes na formatação, mas mandaram muito bem.

2021-03-19 15:48 UTC, lucastrschneider commented on InstalationGuides/ROSGazeboUbuntu.md
> +Vamos agora dar um enfoque em como instalar este software em Ubuntu.
Só um comentário, acho que talvez seja melhor deixar esse comando e seu respectivo gif realmente no final, para a pessoa que esta seguindo o tutorial realmente poder chegar no final e testar sem precisar voltar até aqui para comparar a saída.

Porém, acho necessário deixar um comando aqui para eles entenderem o que tem que acontecer, mas ai poderia ser algo bem genérico que qualquer terminal tem, tipo

```bash
cd --help
```
ou algo assim.

2021-03-19 15:48 UTC, lucastrschneider commented on InstalationGuides/ROSGazeboUbuntu.md
> +```
Nesse bloquinhos de código, da pra colocar o "bash" ali para ele fazer o syntax highlighting

'''bash
comando
'''

~botei aspas em vez do certo lá pq se não ele não mostrava o que eu queria~

2021-03-19 15:48 UTC, lucastrschneider commented on InstalationGuides/ROSGazeboUbuntu.md
> +- [**Preparando o "Ambiente"**](#Preparando-o-"Ambiente")
Só o segundo e quarto links tão funcionando aqui, os outros parecem quebrados, tem que dar uma olhadinha nessas referencias ai

2021-03-19 15:48 UTC, lucastrschneider commented on InstalationGuides/ROSGazeboUbuntu.md
> +--------------------------
Depois de títulos com # ou com ##, o github ja adiciona uma linha embaixo, acho que não precisaria de outra fica um pouco poluido

![image](https://user-images.githubusercontent.com/50970346/111806003-4cdb6380-88b0-11eb-8c48-1d88bdbf9fc7.png)

O mesmo se aplica a alguns outros títulos mais para frente

2021-03-19 15:48 UTC, lucastrschneider commented on InstalationGuides/ROSGazeboWSL.md
> +- [**Instruções para pós instalação**](#Instruções-para-pós-instalação)
Aqui vale o mesmo, tem alguns links quebrados também

2021-03-19 15:48 UTC, lucastrschneider commented on InstalationGuides/ROSGazeboWSL.md
> +--------------------------
Acho que vale a pena dar uma olhada nesses títulos para padronizar. Na versão para Ubuntu, vocês usaram ## para tudo, aqui os títulos do corpo do texto estão com ### (e poir isso faz sentido adicionar a linha embaixo agora se vocês quiserem, pq o header ### não vem com essa linha por padrão)

Mas enfim, eu particularmente acho que tanto faz, escolham o que vocês acharem melhor, mas deixem padronizado em tudo

2021-03-19 15:48 UTC, lucastrschneider commented on InstalationGuides/ROSGazeboWSL.md
> +Em seguida, vamos configurar algumas coisas para que a sua máquina consiga buscar e aceitar o arquivo do servidor fornecedor.
Esse texto ficou repetido

```suggestion
Em seguida, vamos configurar algumas coisas para que a sua máquina consiga buscar e aceitar o arquivo do servidor fornecedor.
```

2021-03-19 15:49 UTC, lucastrschneider commented on InstalationGuides/ROSGazeboUbuntu.md
> +--------------------------
~ops, o haug ja tinha comentado isso~

2021-03-21 18:06 UTC, FelipeGdM commented on InstalationGuides/ROSGazeboUbuntu.md
> +Se quiser aprender mais sobre os softwares e para que servem, veja os documentos explicativos (o que é? / porque usar?) sobre cada software - com certeza vai iluminar melhor a questão.
Aqui você tem a repetição da palavra "software" (o ideal é não repetir palavras e procurar sinônimos), além de que ROS não é um software

```suggestion
Se quiser aprender mais e entender para que servem ROS e Gazebo, veja os documentos explicativos (o que é? / porque usar?) sobre cada um deles - com certeza vai iluminar melhor a questão.
```

2021-03-21 18:06 UTC, FelipeGdM commented on InstalationGuides/ROSGazeboUbuntu.md
> +Neste tutorial, vamos aprender a **instalar** o software chamado **ROS** em sua máquina. Junto com ele, vem o ambiente de simulação **Gazebo**, que permite com que você faça o seu robôzinho andar por
```
Neste tutorial, vamos aprender a **instalar** o software chamado **ROS** em sua máquina. Junto com ele, vem o ambiente de simulação **Gazebo**, que permite com que você faça o seu robôzinho andar por aí.
```

Esse parágrafo está particularmente confuso e contém imprecisões técnicas 

- ROS não é um software, a rigor é um framework de desenvolvimento de software no contexto da robótica
- Gazebo não é um ambiente de simulação, é um simulador efetivamente. Ambiente de simulação é o que nós fizemos (conjunto pista + carrinhos)

2021-03-21 18:49 UTC, FelipeGdM requested changes

2021-03-21 18:49 UTC, FelipeGdM commented on InstalationGuides/ROSGazeboWSL.md
> +Neste tutorial, vamos aprender a **instalar** o software chamado **ROS** em sua máquina. Junto com ele, vem o ambiente de simulação **Gazebo**, que permite com que você faça o seu robôzinho andar por
Mesmo que eu escrevi [aqui](https://github.com/ThundeRatz/ROSGazeboGuide/pull/3/files#r598316296)

2021-03-21 18:49 UTC, FelipeGdM commented on InstalationGuides/ROSGazeboWSL.md
> +Se quiser aprender mais sobre os softwares e para que servem, veja os documentos explicativos (o que é? / porque usar?) sobre cada software - com certeza vai iluminar melhor a questão.
Mesmo que eu escrevi [aqui](https://github.com/ThundeRatz/ROSGazeboGuide/pull/3/files#r598316083) também

2021-03-21 18:49 UTC, FelipeGdM commented on InstalationGuides/ROSGazeboWSL.md
> +Primeiramente, para instalar ROS no Ubuntu em WSL, precisamos configurar os **repositórios Ubuntu** para permitir *"restricted", "universe", e "multiverse"*. Podemos fazer isso com os seguintes coman
Ficou faltando um substantivo depois do verbo "permitir", está confuso saber a que o verbo se refere aqui. Nós sabemos que restricted, universe e multiverse são os nomes dos repositórios, mas os alunos não sabem

```suggestion
Primeiramente, para instalar ROS no Ubuntu em WSL, precisamos configurar os **repositórios Ubuntu** para habilitar os repositórios *"restricted", "universe", e "multiverse"*. Podemos fazer isso com os seguintes comandos:
```

2021-03-21 18:49 UTC, FelipeGdM commented on InstalationGuides/ROSGazeboWSL.md
> +Sucintamente, um repositório é um **servidor** que contém diversos **pacotes**, isto é, arquivos e programas, que estão disponibilizados para usuários instalarem em suas máquinas. No entanto, a confi
Esse parágrafo também está confuso

```suggestion
Sucintamente, um repositório é um **servidor** que contém diversos **pacotes**, isto é, arquivos e programas, que estão disponibilizados para usuários instalarem em suas máquinas. Por padrão, o Ubuntu não habilita o acesso aos repositórios restricted, universe e multiverse mas para instalar o ROS precisamos de acesso a esses servidores.
```

2021-03-21 18:49 UTC, FelipeGdM commented on InstalationGuides/ROSGazeboWSL.md
> +Segue uma tabela que ajuda a entender de maneira simplificada a diferença entre os repositórios.
Eu acredito que não precisa entrar no mérito do que cada repositório guarda, basta dizer que precisamos deles pra instalar o ROS. Esse nível de detalhe não me parece necessário

Dito isso, acho que podemos remover a tabela, basta colocar o link "Se quiser saber mais, confira a documentação oficial"

Ainda sobre a tabela, uma sugestão particular seria substituir "open source" por "livre", mas esse é um gosto pessoal

Uma coisa que é necessário sempre prestar atenção. Nós sabemos quem é a Canonical pq já estamos nesse ramo a muito tempo, mas um bixo vai saber quem eles são? É a primeira vez que esse nome surge no texto.

Esse é um exercício de empatia, é essencial se colocar no lugar do seu público alvo e dificilmente alguém que acabou de entrar na Poli sabe o que/quem é a Canonical. Nesse caso, ou você explica embaixo ou você omite. Eu acharia bem ok fazer uma metonímia e substituir "Canonical" por "Ubuntu", mas aí fica a gosto de quem escreve.

De qualquer forma, acredito que é melhor remover esse trecho inteiro

2021-03-21 18:49 UTC, FelipeGdM commented on InstalationGuides/ROSGazeboWSL.md
> +Vamos agora ajustar o computador para aceitar software da **packages.ros.org** :
O que **packages.ros.org**? Um bixo vai saber o que isso significa?

Como você acabou de investir alguns parágrafos explicando o que é um repositório, é interessante aproveitar esse esforço ao longo do texto

```suggestion
Vamos agora ajustar o computador para aceitar pacotes do **repositório do ROS**:
```

2021-03-21 18:49 UTC, FelipeGdM commented on InstalationGuides/ROSGazeboWSL.md
> +Insira o seguinte comando para salvar as keys na máquina, para a instalação:
```suggestion
Insira o seguinte comando para salvar as chaves do repositório do ROS na sua máquina
```

2021-03-21 18:49 UTC, FelipeGdM commented on InstalationGuides/ROSGazeboWSL.md
> +Estas *keys* são chaves para acesso ao repositório do qual instalaremos nossos arquivos. Se você não fizer esta parte, não terá acesso e não conseguirá instalar.
> "*keys* são chaves" 

_Uma ode à filosofia pós-moderna_

Brincadeiras a parte, não vejo vantagem em ficar usando o termo em inglês pra na sequência dar a sua tradução seca. Acredito que é melhor usar o termo em português direto, de modo a tornar o texto mais simples e mais compreensível

```suggestion
As chaves são necessárias para acesso ao repositório do ROS, do qual instalaremos nossos arquivos. Se você não fizer esta parte, não terá acesso à ele e não conseguirá instalar.
```

2021-03-21 18:49 UTC, FelipeGdM commented on InstalationGuides/ROSGazeboWSL.md
> +Primeiro, vamos dar um update para ter certeza que está tudo atualizado:
O que significa "dar um update"? Quem você está atualizando?

A minha interpretação é que você fez uma metonímia parte-pelo-todo e 

_"Vamos rodar o comando apt update"_  

Se tornou _"Vamos dar um update"_

Novamente vou bater na tecla, é muito importante nos colocar no lugar do nosso público alvo e evitar simplificações que dificultem a compreensão como é o caso dessa daqui.

Seja mais específico, o que vamos fazer aqui?

```suggestion
Primeiro, vamos rodar um comando para atualizar o sistema com as modificações que fizemos até agora
```

2021-03-21 18:49 UTC, FelipeGdM commented on InstalationGuides/ROSGazeboWSL.md
> +## **Preparando o "Ambiente"**
Eu não gosto nem um pouco desse título

O que significa "Ambiente"? Por que você o coloca entre aspas?

Eu digo pra você colocar simplesmente "Preparando o ambiente" ou trocar pra algo bem humorado e pouco específico, como "Toques finais"

2021-03-21 18:49 UTC, FelipeGdM commented on InstalationGuides/ROSGazeboWSL.md
> +É importante configurar o terminal em todo **bash** que se usa ROS.
Temos aqui novamente uma imprecisão técnica no seu texto

A rigor, o que fazemos ao executar esse comando é configurar a nossa sessão do terminal com as variáveis de ambiente do ROS (até aqui, trocar "terminal" por "sessão do terminal" é ok)

Agora, o que significa essa diferenciação de bash e terminal? De fato são coisas diferentes, porém você utiliza os termos de forma intercambiável, ou com uma diferenciação implícita que eu não fui capaz de perceber

```suggestion
Toda vez que você abrir um terminal, é necessário executar o seguinte comando para habilitar o ambiente ROS na sua sessão de terminal
```

2021-03-21 18:49 UTC, FelipeGdM commented on InstalationGuides/ROSGazeboWSL.md
> +Você também pode ajustar para que o "source" deste script seja definido sempre que um novo prompt de comando *shell* for inicializado. Estes comandos fazem isso:
Nem vou comentar que você está usando o termo "shell" com um público alvo leigo sem explicar o que ele significa

```suggestion
Nós somos pessoas preguiçosas, então para não precisar rodar esse comando manualmente sempre que abrimos um novo terminal, nós configuramos o sistema para fazer isso automaticamente pra gente.
```

2021-03-21 18:49 UTC, FelipeGdM commented on InstalationGuides/ROSGazeboWSL.md
> +- zsh
Pode tirar as instruções de zsh

2021-03-21 18:49 UTC, FelipeGdM commented on InstalationGuides/ROSGazeboWSL.md
> +echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
Se quiser, pode complementar a explicação aqui

`.bashrc` é um arquivo especial do sistema com uma lista de comandos a serem executados sempre que um novo terminal é aberto. 

O comando `echo "linhas de texto" >> arquivo` serve para adicionar linhas de texto à um arquivo direto pela linha de comando

2021-03-21 20:49 UTC, GabrielKishida commented
Pessoal! Logo logo vamos dar o merge (finalmente).
Conversei um pouquinho com o @FelipeGdM e demos uma última passada nos tutoriais de instalação ROSGazebo. Revi todas (ou pelo menos, espero que todas) mudanças sugeridas e acredito que esteja tudo certo. Se não estiver, sintam-se à vontade de comentar e/ou mudar!

2021-03-21 22:08 UTC, LucasHaug requested changes

2021-03-21 22:08 UTC, LucasHaug commented on InstalationGuides/ROSGazeboWSL.md
> +![instalação](../assets/gif/ROSGazebo/WSL/3_instalation.gif)
Esse pedaço aqui tem que padronizar com o do Ubuntu, dá pra pegar só o mesmo texto e trocar as imagens.

2021-03-21 22:08 UTC, LucasHaug commented on InstalationGuides/ROSGazeboWSL.md
> +
Acho que dá pra tirar isso e apagar a imagem lá no assets também.

```suggestion
```

2021-03-21 22:13 UTC, LucasHaug requested changes

2021-03-21 22:13 UTC, LucasHaug commented on InstalationGuides/ROSGazeboWSL.md
> +Mas vamos com calma ainda, amigo. Para utilizar o ROS e suas extensões pelo WSL será necessario instalar o Xserver, que também temos um guia de instalação!
```suggestion
Mas vamos com calma ainda, amigo. Para utilizar o ROS e suas extensões pelo WSL será necessário instalar o Xserver, que também temos um guia de instalação!
```

2021-03-21 22:45 UTC, GabrielKishida commented on InstalationGuides/ROSGazeboWSL.md
> +
@VanderSant pode fazer essa mudança pra mim?

2021-03-21 22:49 UTC, GabrielKishida commented on InstalationGuides/ROSGazeboWSL.md
> +**Resposta esperada:**
@VanderSant , pode conferir se nesse documento está padronizado dessa maneira?

2021-03-21 23:47 UTC, VanderSant commented on InstalationGuides/ROSGazeboWSL.md
> +![configurando key e source](../assets/gif/ROSGazebo/WSL/2_source_key.gif)
não prefere colocar "resposta" no lugar de "output" ? parece ser mais fácil de alguém entender

2021-03-21 23:51 UTC, LucasHaug commented on InstalationGuides/ROSGazeboWSL.md
> +![configurando key e source](../assets/gif/ROSGazebo/WSL/2_source_key.gif)
> não prefere colocar "resposta" no lugar de "output" ? parece ser mais fácil de alguém entender

Melhor mesmo, arrumei

2021-03-22 01:04 UTC, LucasHaug requested changes

2021-03-22 01:04 UTC, LucasHaug commented on InstalationGuides/ROSGazeboWSL.md
> +Após abrir o terminal, você poderá inserir comandos que vão realizar tarefas para você. É a maneira principal de se instalar coisas no Ubuntu pelo WSL.
```suggestion
Após abrir o terminal, você poderá inserir comandos que vão realizar tarefas para você. É a maneira principal de se instalar pacotes no WSL.
```

2021-03-22 01:04 UTC, LucasHaug commented on InstalationGuides/ROSGazeboUbuntu.md
> +Após abrir o terminal, você poderá inserir comandos que vão realizar tarefas para você. Quem mexe em Ubuntu trabalha muito com isso, já que é a maneira principal de se instalar coisas nesse sistema o
```suggestion
Após abrir o terminal, você poderá inserir comandos que vão realizar tarefas para você. Quem mexe em Ubuntu trabalha muito com isso, já que é a maneira principal de se instalar pacotes nesse sistema operacional.
```

2021-03-22 01:04 UTC, LucasHaug commented on InstalationGuides/ROSGazeboUbuntu.md
> +A resposta esperada desse comando é o seguinte:
Acho que aqui dá pra deixar do jeito que tava mesmo antes.

```suggestion
Este comando deve abrir o ambiente de simulação **Gazebo**, da seguinte forma:
```

2021-03-22 01:04 UTC, LucasHaug commented on InstalationGuides/ROSGazeboWSL.md
> +![instalação](../assets/gif/ROSGazebo/WSL/3_instalation.gif)
```suggestion
A resposta esperada desses comandos é o seguinte:

![instalação](../assets/gif/ROSGazebo/WSL/3_instalation.gif)
```

2021-03-22 01:20 UTC, LucasHaug requested changes

2021-03-22 01:20 UTC, LucasHaug commented on InstalationGuides/ROSGazeboUbuntu.md
> +O terminal responderá da seguinte forma, apresentando os arquivos da pasta que você se encontra:
```suggestion
O terminal responderá da seguinte forma, apresentando os arquivos e pastas da pasta que você se encontra:
```

2021-03-22 01:20 UTC, LucasHaug commented on InstalationGuides/ROSGazeboWSL.md
> +O terminal responderá da seguinte forma, apresentando os arquivos da pasta que você se encontra:
```suggestion
O terminal responderá da seguinte forma, apresentando os arquivos e pastas da pasta que você se encontra:
```

2021-03-22 01:41 UTC, VanderSant commented on InstalationGuides/ROSGazeboWSL.md
> +O terminal responderá da seguinte forma, apresentando os arquivos da pasta que você se encontra:
"pastas" está repetido haha

2021-03-22 01:44 UTC, LucasHaug commented on InstalationGuides/ROSGazeboWSL.md
> +O terminal responderá da seguinte forma, apresentando os arquivos da pasta que você se encontra:
Ah mas acho que aí tudo bem hsuahsuhasuhaus, porque dentro da pasta tem pastas, dá pra trocar por diretórios também.

2021-03-22 01:45 UTC, VanderSant commented
Acredito que corrigi tudo que precisava, mas até meia noite da para apontar mais coisas

2021-03-22 03:50 UTC, GabrielKishida commented
Boa Vanderson! Mandou muito.

Fiz uma releitura de ambos os arquivos, fiz algumas mudanças (alguns erros gramaticais, e troquei umas palavras para deixar o texto mais claro) mas acredito que agora esteja o fino do fino.
Bom, pelo menos teremos o Test Drive do Rafael em breve para nos dizer o que mais alterar.

Parece que foi ontem que o repositório só tinha 2 commits, e agora tem 53. 


Se ninguém tiver objeções, declaro

2021-03-22 12:05 UTC, FelipeGdM approved these changes
Show de bola, fiz uma pequena adição pra configurar a extensão que gera o índice das páginas, de modo a padronizar bonitinho

2021-03-22 15:10 UTC, lucastrschneider approved these changes
Batata esses dois cometários né, o resto ta show de bola, parabéns aos envolvidos xD

2021-03-22 15:11 UTC, LucasHaug commented on InstalationGuides/ROSGazeboUbuntu.md
> +- [**Índice**](#índice)
Tudo bem que foi gerado automaticamente, mas porque deixar o índice no índice? shuhasuhaushauhs

2021-03-22 15:11 UTC, LucasHaug commented on InstalationGuides/ROSGazeboWSL.md
> +Após abrir o terminal, você poderá inserir comandos que vão realizar tarefas para você. É a maneira principal de se instalar coisas no Ubuntu pelo WSL.
Faltou isso ~~não sei porque eu marquei como resolvido.~~

2021-03-22 15:11 UTC, LucasHaug commented on InstalationGuides/ROSGazeboWSL.md
> +Primeiramente, para instalar ROS no Ubuntu em WSL, precisamos configurar os **repositórios Ubuntu** para habilitar os repositórios *"restricted", "universe", e "multiverse"*. Podemos fazer isso com o
```suggestion
Primeiramente, para instalar ROS no Ubuntu do WSL, precisamos configurar os **repositórios Ubuntu** para habilitar os repositórios *"restricted", "universe", e "multiverse"*. Podemos fazer isso com os seguintes comandos:
```

2021-03-22 15:39 UTC, LucasHaug commented on InstalationGuides/ROSGazeboWSL.md
> +Após abrir o terminal, você poderá inserir comandos que vão realizar tarefas para você. É a maneira principal de se instalar coisas no Ubuntu pelo WSL.
Faltou isso que eu falei https://github.com/ThundeRatz/ROSGazeboGuide/pull/3#discussion_r598370170 @GabrielKishida ahsuhasuhaushuas, percebi depois que o comentário ficou perdido.

2021-03-22 16:04 UTC, LucasHaug commented on .vscode/extensions.json
> +}
Só falta isso daqui, só roubar o editorconfig sei lá do [vss](https://github.com/ThundeRatz/vss_simulation/blob/develop/.editorconfig), e salvar esses dois arquivos aí pra sair esse final sem linha extra.

2021-03-22 17:12 UTC, LucasHaug commented on .vscode/extensions.json
> +}
Só falta isso daqui @GabrielKishida , só roubar o editorconfig sei lá do [vss](https://github.com/ThundeRatz/vss_simulation/blob/develop/.editorconfig), por na raíz do repo, e salvar esses dois arquivos `.json` aí pra sair esse final sem linha extra.

2021-03-22 17:28 UTC, FelipeGdM submitted a review, later dismissed

2021-03-22 22:21 UTC, LucasHaug approved these changes

2021-03-22 22:21 UTC, merged

2021-03-23 00:17 UTC, GabrielKishida commented
https://www.youtube.com/watch?v=kh9vQbwYTH4