Feature/wsl
ThundeRatz/ROSGazeboGuide pull request #5
Opened 2021-03-19 14:12 UTC by Drebt

Fazendo a PR para revisar o texto e garantir que tudo está pronto para entrar na main

2021-03-21 17:54 UTC, FelipeGdM approved these changes
Top demais

2021-03-21 20:55 UTC, LucasHaug approved these changes
Só esperar a outra PR dar merge pra arrumar o link lá do final.

2021-03-21 21:01 UTC, LucasHaug requested changes

2021-03-21 21:01 UTC, LucasHaug commented on InstalationGuides/WSL.md
> +Agora, depois de abrir e aguardar a primiera instalação, você tem que escolher o nome de usuário para a distribuição na linha "Enter nem UNIX username". Ele não precisa ser o mesmo da sua máquina Win
```suggestion
Agora, depois de abrir e aguardar a primeira instalação, você tem que escolher o nome de usuário para a distribuição na linha "Enter nem UNIX username". Ele não precisa ser o mesmo da sua máquina Windows mas tem que ser todo em letras minúsculas.
```

2021-03-21 21:01 UTC, LucasHaug commented on InstalationGuides/WSL.md
> +Com um nume de usuário, agora é apenas colocar o sua senha na linha "Enter new UNIX password" e escrever ela de novo em seguida para confirmar.
```suggestion
Com um nome de usuário, agora é apenas colocar o sua senha na linha "Enter new UNIX password" e escrever ela de novo em seguida para confirmar.
```

2021-03-21 21:01 UTC, LucasHaug commented on InstalationGuides/WSL.md
> +Agora que você tem o WSL com Ubunut 20.04 instalado na sua máquina você pode tirar proveito dos softwares que rodam no Linux, como o ROS/Gazebo, usados na disciplina. Para aprender como instalar eles
```suggestion
Agora que você tem o WSL com Ubuntu 20.04 instalado na sua máquina você pode tirar proveito dos softwares que rodam no Linux, como o ROS/Gazebo, usados na disciplina. Para aprender como instalar eles é só ***[clicar aqui](../InstalationGuides/ROSGazeboWSL.md)*** e seguir as instruções.
```

2021-03-22 10:45 UTC, Drebt commented on InstalationGuides/WSL.md
> +Em seguida, coloque um check na caixinha escrito **Subsistema do Windows para Linux**/*Windows Subsystem for Linux*. Então clique em OK, aguarde as alterações e reinicie seu computardor para aplicar
Esse aqui não tem como mudar o "do". Deixamos assim?

2021-03-22 10:45 UTC, Drebt commented on InstalationGuides/WSL.md
> +Abrindo a página do Ubuntu 20.04 LTS, caso você nunca tenha baixado, é só apertar no botão **Obter**/*Get* e fazer o login com sua conta da Microsoft para adiquirir a distribuição.
Aqui tmb não sei como mudar esse "do" repetido

2021-03-22 14:12 UTC, lucastrschneider reviewed
Muito show, só uns detalhezinhos e pode dar merge acho

2021-03-22 14:12 UTC, lucastrschneider commented on InstalationGuides/WSL.md
> +Todas as imagens vão mostrar os nomes em Português da instalação do Windows, com os nomes de coisas importantes escritos em **negrito**. Caso seu Windows esteja instalado em Inglês eu também vou colo
Só uma sugestão, acho que aqui no finalzinho foi o único lugar do tutorial que usou 1 pessoa. Ai não sei, eu acho meio estranho para um texto assim. ~Quem sou eu?~ ahhauauahsh

Também só mudei um pouquinho o começo para evitar de repetir "nome" seguido assim, mas ai você que sabe, só uma sugestão mesmo.

```suggestion
Todas as imagens vão mostrar uma instalação em Português do Windows, com os nomes de coisas importantes escritos em **negrito**. Ao lado, ficará a tradução para Inglês em *itálico*.
```

2021-03-22 14:12 UTC, lucastrschneider commented on InstalationGuides/WSL.md
> +Em seguida, coloque um check na caixinha escrito **Subsistema do Windows para Linux**/*Windows Subsystem for Linux*. Então clique em OK, aguarde as alterações e reinicie seu computardor para aplicar
Você diz o "do" de "Subsistema do Windows para Linux"? Acho que como é assim que ta escrito na imagem e no gif das telas do Windows, melhor deixar igualzinho msm. A própria Microsoft escreve dos dois jeitos nos docs deles em port kkkkkk

2021-03-22 14:12 UTC, lucastrschneider commented on InstalationGuides/WSL.md
> +Agora, depois de abrir e aguardar a primeira instalação, você tem que escolher o nome de usuário para a distribuição na linha "Enter nem UNIX username". Ele não precisa ser o mesmo da sua máquina Win
```suggestion
Agora, depois de abrir e aguardar a primeira instalação, você tem que escolher o nome de usuário para a distribuição na linha "Enter new UNIX username". Ele não precisa ser o mesmo da sua máquina Windows mas tem que ser todo em letras minúsculas.
```
nem -> new

2021-03-22 15:17 UTC, LucasHaug commented on InstalationGuides/WSL.md
> +Em seguida, coloque um check na caixinha escrito **Subsistema do Windows para Linux**/*Windows Subsystem for Linux*. Então clique em OK, aguarde as alterações e reinicie seu computardor para aplicar
> Esse aqui não tem como mudar o "do". Deixamos assim?

Calma o "do" pintado você tá falando? Acho que ele só tá pintado, porque na sugestão ele tá interpretando como código aí um "do while" ahahahahshahashaah

2021-03-22 16:38 UTC, Drebt commented on InstalationGuides/WSL.md
> +Em seguida, coloque um check na caixinha escrito **Subsistema do Windows para Linux**/*Windows Subsystem for Linux*. Então clique em OK, aguarde as alterações e reinicie seu computardor para aplicar
Ah, então batata. Achei que os vermelhos era pra destacar coisas repetidas

2021-03-22 16:39 UTC, Drebt commented on InstalationGuides/WSL.md
> +Todas as imagens vão mostrar os nomes em Português da instalação do Windows, com os nomes de coisas importantes escritos em **negrito**. Caso seu Windows esteja instalado em Inglês eu também vou colo
Ficou legal, bem identificado. vou dar commit

2021-03-22 20:28 UTC, FelipeGdM approved these changes

2021-03-22 20:48 UTC, LucasHaug commented
Só não aprovei ainda, porque tô esperando dar maerge na PR #1 pra poder arrumar o link no final do arquivo aushuashaushushau

2021-03-22 20:50 UTC, lucastrschneider commented
> Só não aprovei ainda, porque tô esperando dar maerge na PR #1 pra poder arrumar o link no final do arquivo aushuashaushushau

Aprova ai, o link ta certo, já ta com o nome que o arquivo vai ter, tanto que ele nem funciona nessa branch, leva para uma página não existente, mas que vai existir

2021-03-22 20:51 UTC, LucasHaug approved these changes

2021-03-22 20:52 UTC, merged