Feature/why ros
ThundeRatz/ROSGazeboGuide pull request #8
Opened 2021-03-24 03:32 UTC by mariarezende07

Eu fiz um textinho explicando as vantagens de utilizar ROS. Ele acabou ficando meio curto, então por favor deem uma lida e me digam se eu devo adicionar algo a mais e etc.

2021-03-24 17:26 UTC, FelipeGdM reviewed
Show de bola o texto, a pergunta "Por que usar ROS?" está completamente respondida aqui. 

Se você quiser escrever mais, acredito que um exemplo pode ajudar a sedimentar o conceito na cabeça da galera, tipo

> Imagine que você vai desenvolver um robô de mineração lunar. Pense em todas as tarefas necessárias para fazer esse robô funcionar. Quantas dessas tarefas não estão diretamente ligadas à tarefa que realmente importa (mineração na Lua). ROS é top pq faz as coisas chatas e permite que você foque no que realmente importa

Na dúvida, acho que dá pra preencher com mais exemplos pra situar a galera no contexto de desenvolvimento de software pra robôs. Não acho que seja essencial, do jeito que tá já está bem daora

Acredito que temos alguns probleminhas de formatação, várias linhas tem whitespaces, o que buga a formatação do markdown. Recomendo instalar a extensão "Markdownlint" `davidanson.vscode-markdownlint`, que avisa pra você a respeito de problemas como esse

2021-03-24 17:26 UTC, FelipeGdM commented on ROS/WhyToUse.md
> +Além disso, o ROS torna possível a utilização conjunta de nodes escritos em C++ e Python. Com isso, a cooperação entre desenvolvedores é ampliada, permitindo que pessoas que têm conhecimento em lingu
Aqui temos uma questão filosófica. O ROS oferece suporte **oficial** pra python e C++, mas existem diversos ports pra outras linguagens de programação que são desenvolvidos e mantidos pela comunidade. Desde [ROS em Rust](https://github.com/adnanademovic/rosrust) até mesmo [ROS em NodeJS](http://wiki.ros.org/rosnodejs) (inclusive, boatos que existe uma implementação profana de ROS em PHP :eyes:). O céu é o limite

![image](https://user-images.githubusercontent.com/1054087/112352897-f3a57280-8ca9-11eb-827e-d2c70262376a.png)

2021-03-24 17:26 UTC, FelipeGdM commented on ROS/WhyToUse.md
> +ROS é definitivamente uma ferramenta poderosa no aprendizado de sistemas robóticos, capaz de ajudar você, futuro Engenheiro Mecatrônico, a desenvolver projetos de inovação com facilidade e rapidez. A
Acredito que "Engenheiro Mecatrônico" não tem letra maiúscula aqui

Não estou familiarizado com a expressão "projeto de inovação", talvez "projeto inovador" faça mais sentido

2021-03-28 21:20 UTC, LucasHaug requested changes

2021-03-28 21:20 UTC, LucasHaug commented on ROS/WhyToUse.md
> +Agora que você já sabe o que é o ROS, é importante entender por que utilizamos ele em projetos robóticos. Esta ferramenta pode auxiliar no desenvolvimento de projetos e agilizar muitos trabalhos que,
Eu acho que prefiro escrever assim, mas é só uma sugestão ahahahahahahah

```suggestion
Agora que você já sabe o que é o ROS, é importante entender porque utilizamos ele em projetos de robótica. Esta ferramenta pode auxiliar no desenvolvimento de projetos e agilizar muitos trabalhos que, sem ela, teriam que ser feitos manualmente, além de proporcionar um ambiente *open-source* que auxilia desenvolvedores mais experientes. Para que possamos responder a pergunta "Por que utilizar o ROS" iremos explorar alguns benefícios que essa ferramenta pode nos proporcionar.
```

2021-03-28 21:20 UTC, LucasHaug commented on ROS/WhyToUse.md
> +Além disso, o tamanho da comunidade do ROS traz consigo a existência de uma grande diversidade de projetos, tornando possível a utilização de diversos *packages* externos durante o desenvolvimento de
Acho que dá pra deixar em português aqui

```suggestion
Além disso, o tamanho da comunidade do ROS traz consigo a existência de uma grande diversidade de projetos, tornando possível a utilização de diversos pacotes externos durante o desenvolvimento de um projeto. Isso permite que o desenvolvedor não desperdice tempo com a criação de *joysticks*, sensores e outras funcionalidades, e se foque apenas na parte principal do projeto.
```

2021-03-28 21:20 UTC, LucasHaug commented on ROS/WhyToUse.md
> +<img src = 'https://roboticsbackend.com/wp-content/uploads/2019/02/reinvent_the_wheel.jpg' width='500px' >
Acho que dá pra colocar essa e as imagens de baixo dentro da pasta `assets` do repositório, pra que sei lá se essas imagens saírem desses sites, não fique com uma referência quebrada e a gente sem a imagem. ~~Tem uma imagem que tá com link quebrado já mais pra baixo.~~

2021-03-28 21:20 UTC, LucasHaug commented on ROS/WhyToUse.md
> +Além disso, o ROS torna possível a utilização conjunta de nodes escritos em C++ e Python. Com isso, a cooperação entre desenvolvedores é ampliada, permitindo que pessoas que têm conhecimento em lingu
```suggestion
Além disso, o ROS torna possível a utilização conjunta de *nodes* escritos em C++ e Python. Com isso, a cooperação entre desenvolvedores é ampliada, permitindo que pessoas que têm conhecimento em linguagens diferentes possam trabalhar juntas no mesmo projeto, facilitando o desenvolvimento e a implementação de funcionalidades. 
```

2021-03-28 21:20 UTC, LucasHaug commented on ROS/WhyToUse.md
> +<hr>
Acho que dá pra usar a sintaxe do markdown direto aqui 

```suggestion
---
```

2021-03-28 21:20 UTC, LucasHaug commented on ROS/WhyToUse.md
> +<li><a href= http://gazebosim.org/tutorials> Tutoriais do Gazebo </a>
Se quiser dá pra usar markdown direto aqui mesmo ao invés de colocar html

```suggestion
[Tutoriais da Wiki de ROS](http://wiki.ros.org/ROS/Tutorials)
[Tutoriais do ConstructSim](https://www.theconstructsim.com/category/ros-tutorials)
[Tutoriais do Gazebo](http://gazebosim.org/tutorials)
```

2021-03-28 21:22 UTC, LucasHaug commented
E ah só lembrando de resolver os conflitos com a develop com as coisas que eu mexi na PR #7, se precisar de ajuda, só falar.

2021-03-29 13:35 UTC, FelipeGdM commented on ROS/WhyToUse.md
> +Agora que você já sabe o que é o ROS, é importante entender por que utilizamos ele em projetos robóticos. Esta ferramenta pode auxiliar no desenvolvimento de projetos e agilizar muitos trabalhos que,
@LucasHaug quero ver você explicar porque esse porque aí é junto hahahaha

2021-03-29 13:57 UTC, LucasHaug commented on ROS/WhyToUse.md
> +Agora que você já sabe o que é o ROS, é importante entender por que utilizamos ele em projetos robóticos. Esta ferramenta pode auxiliar no desenvolvimento de projetos e agilizar muitos trabalhos que,
Ish nossa agora bateu a dúvida haushuahsuhasuhas, vou fazer uma sugestão mais safe.

2021-03-29 13:59 UTC, LucasHaug commented on ROS/WhyToUse.md
> +Agora que você já sabe o que é o ROS, é importante entender por que utilizamos ele em projetos robóticos. Esta ferramenta pode auxiliar no desenvolvimento de projetos e agilizar muitos trabalhos que,
Editei a sugestão aí ahusushaushaushus

2021-03-30 17:59 UTC, lucastrschneider approved these changes
Achei sensacional o texto! formatação também parece que está tudo check, mandou bem

2021-03-31 14:57 UTC, FelipeGdM approved these changes
Show de bola! Uma última sugestão, se vc quiser centralizar as imagens vc pode adicionar um `{: .mx-auto}` logo depois delas, seguindo as instruções do tema [Just the docs](https://pmarsceill.github.io/just-the-docs/docs/utilities/layout/#spacing) que estamos usando no Github pages

2021-04-02 01:49 UTC, febagni reviewed
Excelente texto! Mandou bem demais! Pelo que eu vi, tá check!

2021-04-02 14:23 UTC, LucasHaug requested changes

2021-04-02 14:23 UTC, LucasHaug commented on ROS/WhyToUse.md
> +{: .mx-auto}
Então as imagens aqui tem que colocar com caminho relativo, pro Github Pages achar as imagens. E acho que a tag lá é colada na imagem.

```suggestion
![Reinvent the wheel](../assets/img/WhyROS/reinvent_the_wheel.jpg) {: .mx-auto}
```

2021-04-02 14:23 UTC, LucasHaug commented on ROS/WhyToUse.md
> +{: .mx-auto}
```suggestion
![ROS with libraries](../assets/img/WhyROS/ros_with_libraries.jpg) {: .mx-auto}
```

2021-04-02 14:23 UTC, LucasHaug commented on ROS/WhyToUse.md
> +{: .mx-auto}
```suggestion

![ROS multi-language](/assets/img/WhyROS/ros_language_agnostic.png) {: .mx-auto}
```

2021-04-02 14:23 UTC, LucasHaug commented on ROS/WhyToUse.md
> +{: .mx-auto}
```suggestion
![Gazebo Simulation](../assets/img/WhyROS/gazebo_simulation.png) {: .mx-auto}
```

2021-04-02 15:09 UTC, LucasHaug requested changes

2021-04-02 15:09 UTC, LucasHaug commented on ROS/WhyToUse.md
> +Além disso, o ROS torna possível a utilização conjunta de *nodes* escritos em linguagens diferentes. Com isso, a cooperação entre desenvolvedores é ampliada, permitindo que pessoas que têm conhecimen
Essa info de nodes em diferentes linguagens tá repetida em relação ao parágrafo de cima.

2021-04-03 14:43 UTC, LucasHaug approved these changes

2021-04-03 14:44 UTC, merged