Feature/instalation guides xserver
ThundeRatz/ROSGazeboGuide pull request #9
Opened 2021-03-24 16:28 UTC by VanderSant

Estou fazendo essa PR para saber o que eu posso melhorar

2021-03-25 01:15 UTC, lucastrschneider requested changes
Boa, tava precisando disso pq ainda não fiz isso no meu windows uahsuhauhshahu

2021-03-25 01:15 UTC, lucastrschneider commented on InstalationGuides/XServer.md
> +Após a instalação do WSL, ROS/Gazebo e Xserver, o seu computador está pronto para as experiencias que serão realizadas nas aulas!
```suggestion
Após a instalação do WSL, ROS/Gazebo e Xserver, o seu computador está pronto para as experiências que serão realizadas nas aulas!
```

2021-03-25 01:15 UTC, lucastrschneider commented on InstalationGuides/XServer.md
> + ***[clique aqui]()***  para executar todo o projeto no seu Windows!
Sla, parece que clicando aí ele vai executar ja tudo para você auhsuahshuhashhu

```suggestion
Para aprender a executar seu projeto no Windows, ***[clique aqui]()*** 
```

2021-03-26 00:00 UTC, LucasHaug requested changes
Primeiramente muito show, eu fiz algumas sugestões ~~(várias sugestões de tirar linhas sobrando hsuhuahsuahsuhs)~~. 

Acho que talvez seria legal adicionar em algum lugar falando que tipo você só precisa rodar isso uma vez né, que depois ele fica rodando no fundo, se você for no canto inferior direito dá pra ver lá que tem o Xserver rodando.  Não sei dizer o que acontece se você der launch várias vezes no display 0, se pá dá nada ahsuahsuhauhsuahsu, mas tipo se você deixar lá no começo em -1 pra ele ir alocando sozinho, na primeira vez ele vai pro 0 beleza, mas depois ele vai aumentando o número e você pode acabar com vários Xserver pra diferentes números de display rodando hausaushaushus. 

Uma outra coisa que queria discutir é sobre colocar um teste pra eles verem funcionando, tipo nesse [post aqui do fórum](https://forum.thunderatz.org/viewtopic.php?f=485&t=3541#p55451), mas aí teria que falar que o WSL precisa estar instalado pra isso.

2021-03-26 00:00 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +![Logo do XServer no windowsa](../assets/img/logo_Xserver.png)
```suggestion
![Logo do XServer no windows](../assets/img/logo_Xserver.png)
```

2021-03-26 00:00 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +
```suggestion

```

2021-03-26 00:00 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +Não é necessário ter o WSL e ROS/Gazebo instalado no seu computador para seguir esse tutorial, porém recomendo que façam esse tutorial por último.
```suggestion
Não é necessário ter o WSL e ROS/Gazebo instalado no seu computador para seguir esse tutorial, porém é recomendado que se faça esse tutorial por último.
```

2021-03-26 00:00 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +
```suggestion

```

2021-03-26 00:00 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +
```suggestion

```

2021-03-26 00:00 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +
```suggestion

```

2021-03-26 00:00 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +
```suggestion

```

2021-03-26 00:00 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +
```suggestion

```

2021-03-26 00:00 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +- Execute e instale o arquivo **"vcxsrv-64.1.20.9.0.installer"**
Aqui acho melhor sei lá colocar uns "x" no lugar dos números e falar que eles estão no lugar da versão, porque vai que atualizam a versão, não precisa ser essa daí em específico.

2021-03-26 00:00 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +
```suggestion

```

2021-03-26 00:00 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +
```suggestion

```

2021-03-26 00:00 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +Após baixar e executar o arquivo "vcxsrv-64.1.20.9.0.installer", ele irá criar um arquivo chamado **Xlaunch** na sua área de trabalho (Desktop, se o seu computador estiver em inglês)
Idem sobre a versão aqui. ~~Mas nossa deixar na área de trabalho hasuahuahushaush~~

2021-03-26 00:00 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +    - Deixe **display number = 0**.
```suggestion
    - Deixe **"display number"** em **0**.
```

2021-03-26 00:00 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +
```suggestion

```

2021-03-26 00:00 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +
```suggestion

```

2021-03-26 00:00 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +
```suggestion

```

2021-03-26 00:01 UTC, LucasHaug commented
E ah vai ter que dar merge na PR #7 antes pra atulizar com as coisas do Github Pages aqui.

2021-03-28 21:04 UTC, LucasHaug requested changes

2021-03-28 21:04 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +***[Clique aqui](../InstalationGuides/ROSGazeboWSL.md)*** para ser direcionado ao tutorial de instalação do ROS/Gazebo
```suggestion
***[Clique aqui](../InstalationGuides/WSL.md)*** para ser direcionado ao tutorial de instalação do WSL.

***[Clique aqui](../InstalationGuides/ROSGazeboWSL.md)*** para ser direcionado ao tutorial de instalação do ROS/Gazebo.
```

2021-03-28 21:04 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +- **Baixe** o arquivo **VcXsrv Windows X Server** e **salve** no seu local de preferencia:
```suggestion

## **Download e execução do arquivo VcXsrv**

- **Baixe** o arquivo **VcXsrv Windows X Server** e **salve** no seu local de preferencia:
```

2021-03-28 21:04 UTC, LucasHaug commented on InstalationGuides/XServer.md
> + ***[clique aqui](https://sourceforge.net/projects/vcxsrv/)*** para baixar o VcXsrv Windows X Server
```suggestion
    - ***[Clique aqui](https://sourceforge.net/projects/vcxsrv/)*** para baixar o VcXsrv Windows X Server.
```

2021-03-28 21:04 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +![execute o XServer](../assets/gif/XServer/1_executando_VcXsrv.gif)
```suggestion

![download XServer](../assets/gif/XServer/0_baixando_VcXsrv.gif)

- Execute e instale o arquivo **"vcxsrv-64.1.x.x.x.installer"** (obs.: os 'x' estão no lugar da versão, ou seja, desde que estaja dentro da "vcxsrv-64.1", está tudo bem baixar essa opção)
    
    - O arquivo, a priori, já vem com as configurações adequadas, porém, certifique-se que a opção de instalação está "full" e que todas as "caixinhas" estão selecionadas. 
    
![execute o XServer](../assets/gif/XServer/1_executando_VcXsrv.gif)

```

2021-03-29 03:29 UTC, VanderSant commented on InstalationGuides/XServer.md
> +    - Deixe **"display number"** em **-1**.
vou ter que mudar o gif de novo hahaha mas ok

2021-03-29 03:35 UTC, VanderSant commented on InstalationGuides/XServer.md
> +![execute o XServer](../assets/gif/XServer/1_executando_VcXsrv.gif)
acredite ou não, mas eu tinha deixado tudo juntinha pq achei que vc iria preferir hahahah

2021-03-29 04:22 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +    - Deixe **"display number"** em **-1**.
Noooosssa justo verdade, sorry shuahsuahsuahsu. Mas ah só reverter esse commit aqui 01633ba0bd97c906cc36ad66957f8ded766f18b6 né

2021-03-29 13:51 UTC, FelipeGdM requested changes
Topzeira

Acredito que podemos simplificar as instruções se não for necessário usar o nano. Apontei também um ou outro erro de concordância que deve ter passado batido.

2021-03-29 13:51 UTC, FelipeGdM commented on InstalationGuides/XServer.md
> +Após baixar e executar o arquivo "vcxsrv-64.1.x.x.x.installer", ele irá criar um arquivo chamado **Xlaunch** na sua área de trabalho (Desktop, se o seu computador estiver em inglês)
```suggestion
Após baixar e executar o arquivo "vcxsrv-64.1.x.x.x.installer", ele irá criar um arquivo chamado **Xlaunch** na sua área de trabalho (desktop, se o seu computador estiver em inglês)
```
Se tá com letra minúscula em portuguẽs, coloca em letra minúscula em inglês também

2021-03-29 13:51 UTC, FelipeGdM commented on InstalationGuides/XServer.md
> +nano ~/.bashrc
No [guia de instalação do ROS](https://github.com/ThundeRatz/ROSGazeboGuide/blob/main/InstalationGuides/ROSGazeboWSL.md#toques-finais), nós fazemos uma edição no `.bashrc` direto pela linha de comando, acredito que podemos fazer o mesmo aqui pra simplificar o processo

Ao invés de 

```bash
nano ~/.bashrc
export DISPLAY=:0 # linha adicionada no arquivo
```

Podemos fazer direto

```bash
echo "export DISPLAY=:0" >> ~/.bashrc
```

O caminho tem menos passos intermediários. Outra mudança que eu acredito que é interessante é mover essas instruções pra cima, pois elas fazem parte do conjunto "Instruções de instalação", não "Instruções de teste". Digo, não é necessário fazer isso _toda vez_ que se abrir o XServer, só no momento da instação

2021-03-29 13:51 UTC, FelipeGdM commented on InstalationGuides/XServer.md
> +Depois dessa série de comando, deve aparecer três engrenagens coloridas girando:
```suggestion
Depois dessa série de comandos, deve aparecer três engrenagens coloridas girando:
```

2021-03-29 13:51 UTC, FelipeGdM commented on InstalationGuides/XServer.md
> +- **Digite** no terminal o seguintes comando:
```suggestion
- **Digite** no terminal o seguinte comando:
```

2021-03-29 13:51 UTC, FelipeGdM commented on InstalationGuides/XServer.md
> +- **Instale** o pacote `mesa-utilis` com seguinte comando:
```suggestion
- **Instale** o pacote `mesa-utilis` com o seguinte comando:
```

2021-03-29 15:30 UTC, Drebt commented
Seria interessante explicar como salva as configurações já que o aluno sempre tem que abrir o XServer quando reinicia o PC? Ai não precisa decorar o que tem que ativar e o número do display

2021-04-02 15:51 UTC, FelipeGdM submitted a review, later dismissed
Show de bola, agora acho que tá check

2021-04-03 15:51 UTC, LucasHaug requested changes
~~Eu sou chato sorry~~

2021-04-03 15:51 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +Não é necessário ter o ROS/Gazebo instalado no seu computador para seguir esse tutorial, mas é necessario o WSL para os toques finais. Contudo, recomendo que faça esse tutorial por último.
```suggestion
Não é necessário ter o ROS/Gazebo instalado no seu computador para seguir esse tutorial, mas é necessario o WSL para os toques finais. Dessa forma, recomendo que faça esse tutorial por último.
```

2021-04-03 15:51 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +- Execute e instale o arquivo **"vcxsrv-64.1.x.x.x.installer"** (obs.: os 'x' estão no lugar da versão, ou seja, desde que estaja dentro da "vcxsrv-64.1", está tudo bem baixar essa opção)
```suggestion
- Execute e instale o arquivo **"vcxsrv-64.1.x.x.x.installer"** (obs.: os 'x' estão no lugar da versão, ou seja, desde que estaja dentro da "vcxsrv-64.1", está tudo bem baixar essa opção).
```

2021-04-03 15:51 UTC, LucasHaug commented on InstalationGuides/XServer.md
>  parent: Guias de Instalação
Tem lugar que tá "x server" e lugar que tá "xserver", acho que dá pra padronizar com "x server". ~~Eu comentei nessa linha, mas é na de cima que tem q mexer, eh que não tinha como comentar lá.~~ 

Tem que arrumar no ìndice principal do repositório também e no arquivo de instalação do ROS/Gazebo no WSL.

2021-04-03 15:51 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +# **Como Instalar o Xserver no Windows**
```suggestion
# **Como Instalar o X server no Windows**
```

2021-04-03 15:51 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +Neste tutorial, vamos aprender a **instalar** o Xorg Server chamado **Xserver** em sua máquina.
```suggestion
Neste tutorial, vamos aprender a **instalar** o Xorg Server chamado **X server** em sua máquina.
```

2021-04-03 15:51 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +Após a instalação do WSL, ROS/Gazebo e Xserver, o seu computador está pronto para as experiências que serão realizadas nas aulas!
```suggestion
Depois disso, está pronta a instalação do X server.

Após a instalação do WSL, ROS/Gazebo e X server, o seu computador está pronto para as experiências que serão realizadas nas aulas!
```

2021-04-03 15:51 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +    - **Nomeie** o arquivo como preferir e **Salve** no seu local de preferência.
```suggestion
    - **Nomeie** o arquivo como preferir e **salve** no seu local de preferência.
```

2021-04-03 15:51 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +Caso não tenha feito isso ainda, ***[Clique aqui](../InstalationGuides/WSL.md)*** para ser direcionado ao tutorial de instalação do WSL.
```suggestion
Caso não tenha feito isso ainda, ***[clique aqui](../InstalationGuides/WSL.md)*** para ser direcionado ao tutorial de instalação do WSL.
```

2021-04-03 15:51 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +- **Abra** o **terminal** do Ubuntu no Windows e digite o seguinte comando:
```suggestion
- Caso esteja usando o **WSL1**, **abra** o **terminal** do Ubuntu no Windows e digite o seguinte comando:
```

2021-04-03 15:51 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +Observação:
```suggestion
```

2021-04-03 15:53 UTC, LucasHaug requested changes

2021-04-03 15:53 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +- Execute o **Xlaunch**
```suggestion
- Execute o **Xlaunch**.
```

2021-04-03 15:53 UTC, LucasHaug commented on InstalationGuides/XServer.md
> +Para aprender a executar seu projeto no Windows, ***[clique aqui](../HowToRun/RunOnWSL.md)***
```suggestion
Para aprender a executar seu projeto no Windows, ***[clique aqui](../HowToRun/RunOnWSL.md)***. 
```

2021-04-03 21:15 UTC, LucasHaug approved these changes

2021-04-03 21:16 UTC, merged